var iconName = [
  'Access Time',
  'Accessibility',
  'Accessibility Checkmark',
  'Add',
  'Add Circle',
  'Add Square',
  'Add Subtract Circle',
  'Airplane',
  'Airplane Take Off',
  'Album',
  'Album Add',
  'Alert',
  'Alert Off',
  'Alert On',
  'Alert Snooze',
  'Alert Urgent',
  'Align Bottom',
  'Align Center Horizontal',
  'Align Center Vertical',
  'Align Left',
  'Align Right',
  'Align Top',
  'Animal Cat',
  'Animal Dog',
  'Animal Rabbit',
  'Animal Turtle',
  'App Folder',
  'App Generic',
  'App Recent',
  'App Store',
  'App Title',
  'Approvals App',
  'Apps',
  'Apps Add In',
  'Apps List',
  'Apps List Detail',
  'Archive',
  'Arrow Autofit Content',
  'Arrow Autofit Down',
  'Arrow Autofit Height',
  'Arrow Autofit Height Dotted',
  'Arrow Autofit Up',
  'Arrow Autofit Width',
  'Arrow Autofit Width Dotted',
  'Arrow Bidirectional Up Down',
  'Arrow Bounce',
  'Arrow Circle Down',
  'Arrow Circle Down Double',
  'Arrow Circle Down Right',
  'Arrow Circle Down Split',
  'Arrow Circle Left',
  'Arrow Circle Right',
  'Arrow Circle Up',
  'Arrow Circle Up Left',
  'Arrow Clockwise',
  'Arrow Clockwise Dashes',
  'Arrow Collapse All',
  'Arrow Counterclockwise',
  'Arrow Counterclockwise Dashes',
  'Arrow Curve Down Left',
  'Arrow Down',
  'Arrow Down Left',
  'Arrow Download',
  'Arrow Enter Left',
  'Arrow Enter Up',
  'Arrow Expand',
  'Arrow Export Ltr',
  'Arrow Export Up',
  'Arrow Forward',
  'Arrow Growth',
  'Arrow Hook Down Left',
  'Arrow Hook Down Right',
  'Arrow Hook Up Left',
  'Arrow Hook Up Right',
  'Arrow Import',
  'Arrow Left',
  'Arrow Maximize',
  'Arrow Maximize Vertical',
  'Arrow Minimize',
  'Arrow Minimize Vertical',
  'Arrow Move',
  'Arrow Next',
  'Arrow Previous',
  'Arrow Redo',
  'Arrow Repeat All',
  'Arrow Repeat All Off',
  'Arrow Reply',
  'Arrow Reply All',
  'Arrow Reply Down',
  'Arrow Reset',
  'Arrow Right',
  'Arrow Rotate Clockwise',
  'Arrow Rotate Counterclockwise',
  'Arrow Routing',
  'Arrow Routing Rectangle Multiple',
  'Arrow Sort',
  'Arrow Sort Down',
  'Arrow Sort Up',
  'Arrow Square Down',
  'Arrow Swap',
  'Arrow Sync',
  'Arrow Sync Circle',
  'Arrow Trending',
  'Arrow Trending Checkmark',
  'Arrow Trending Lines',
  'Arrow Trending Settings',
  'Arrow Turn Bidirectional Down Right',
  'Arrow Turn Right',
  'Arrow Undo',
  'Arrow Up',
  'Arrow Up Left',
  'Arrow Up Right',
  'Arrow Upload',
  'Arrows Bidirectional',
  'Attach',
  'Attach Arrow Right',
  'Attach Text',
  'Auto Fit Height',
  'Auto Fit Width',
  'Autocorrect',
  'Autofit Content',
  'Autosum',
  'Backpack',
  'Backpack Add',
  'Backspace',
  'Badge',
  'Balloon',
  'Barcode Scanner',
  'Battery0',
  'Battery1',
  'Battery2',
  'Battery3',
  'Battery4',
  'Battery5',
  'Battery6',
  'Battery7',
  'Battery8',
  'Battery9',
  'Battery Charge',
  'Battery Checkmark',
  'Battery Full',
  'Battery Saver',
  'Battery Warning',
  'Beach',
  'Beaker',
  'Beaker Edit',
  'Bed',
  'Bin Full',
  'Block',
  'Bluetooth',
  'Bluetooth Connected',
  'Bluetooth Disabled',
  'Bluetooth Searching',
  'Blur',
  'Board',
  'Board Split',
  'Book',
  'Book Add',
  'Book Clock',
  'Book Coins',
  'Book Compass',
  'Book Contacts',
  'Book Database',
  'Book Exclamation Mark',
  'Book Globe',
  'Book Information',
  'Book Letter',
  'Book Number',
  'Book Open',
  'Book Open Globe',
  'Book Open Microphone',
  'Book Pulse',
  'Book Question Mark',
  'Book Question Mark Rtl',
  'Book Search',
  'Book Star',
  'Book Theta',
  'Book Toolbox',
  'Bookmark',
  'Bookmark Add',
  'Bookmark Multiple',
  'Bookmark Off',
  'Border',
  'Border All',
  'Border Bottom',
  'Border Bottom Double',
  'Border Bottom Thick',
  'Border Left',
  'Border Outside',
  'Border Outside Thick',
  'Border Right',
  'Border Top',
  'Border Top Bottom',
  'Border Top Bottom Double',
  'Border Top Bottom Thick',
  'Bot',
  'Bot Add',
  'Bowl Chopsticks',
  'Box Edit',
  'Box Toolbox',
  'Braces Variable',
  'Brain Circuit',
  'Branch',
  'Branch Compare',
  'Branch Fork',
  'Briefcase',
  'Briefcase Medical',
  'Briefcase Off',
  'Broad Activity Feed',
  'Broom',
  'Bug',
  'Building',
  'Building Bank',
  'Building Bank Link',
  'Building Bank Toolbox',
  'Building Factory',
  'Building Government',
  'Building Multiple',
  'Building Retail',
  'Building Retail Money',
  'Building Retail Shield',
  'Building Retail Toolbox',
  'Building Shop',
  'Building Skyscraper',
  'Calculator',
  'Calculator Multiple',
  'Calendar3 Day',
  'Calendar Add',
  'Calendar Agenda',
  'Calendar Arrow Down',
  'Calendar Assistant',
  'Calendar Cancel',
  'Calendar Checkmark',
  'Calendar Clock',
  'Calendar Day',
  'Calendar Edit',
  'Calendar Empty',
  'Calendar Error',
  'Calendar Ltr',
  'Calendar Month',
  'Calendar Multiple',
  'Calendar Overdue',
  'Calendar Person',
  'Calendar Question Mark',
  'Calendar Reply',
  'Calendar Rtl',
  'Calendar Star',
  'Calendar Sync',
  'Calendar Today',
  'Calendar Week Numbers',
  'Calendar Week Start',
  'Calendar Work Week',
  'Call',
  'Call Add',
  'Call Checkmark',
  'Call Dismiss',
  'Call End',
  'Call Forward',
  'Call Inbound',
  'Call Missed',
  'Call Outbound',
  'Call Park',
  'Call Pause',
  'Call Prohibited',
  'Calligraphy Pen',
  'Camera',
  'Camera Add',
  'Camera Dome',
  'Camera Off',
  'Camera Switch',
  'Caret',
  'Caret Down',
  'Caret Down Left',
  'Caret Left',
  'Caret Right',
  'Caret Up',
  'Cart',
  'Cast',
  'Cellular3g',
  'Cellular4g',
  'Cellular5g',
  'Cellular Data1',
  'Cellular Data2',
  'Cellular Data3',
  'Cellular Data4',
  'Cellular Data5',
  'Cellular Data Cellular Off',
  'Cellular Data Cellular Unavailable',
  'Cellular Data Unavailable',
  'Cellular Warning',
  'Center Horizontal',
  'Center Vertical',
  'Certificate',
  'Channel',
  'Channel Add',
  'Channel Alert',
  'Channel Arrow Left',
  'Channel Dismiss',
  'Channel Share',
  'Channel Subtract',
  'Chart Person',
  'Chat',
  'Chat Bubbles Question',
  'Chat Help',
  'Chat Multiple',
  'Chat Off',
  'Chat Settings',
  'Chat Video',
  'Chat Warning',
  'Check',
  'Checkbox1',
  'Checkbox2',
  'Checkbox Arrow Right',
  'Checkbox Checked',
  'Checkbox Indeterminate',
  'Checkbox Person',
  'Checkbox Unchecked',
  'Checkbox Warning',
  'Checkmark',
  'Checkmark Circle',
  'Checkmark Lock',
  'Checkmark Square',
  'Chevron Circle Down',
  'Chevron Circle Right',
  'Chevron Down',
  'Chevron Left',
  'Chevron Right',
  'Chevron Up',
  'Chevron Up Down',
  'Circle',
  'Circle Edit',
  'Circle Half Fill',
  'Circle Line',
  'Circle Small',
  'City',
  'Class',
  'Classification',
  'Clear Formatting',
  'Clipboard',
  'Clipboard Arrow Right',
  'Clipboard Checkmark',
  'Clipboard Code',
  'Clipboard Error',
  'Clipboard Heart',
  'Clipboard Image',
  'Clipboard Letter',
  'Clipboard Link',
  'Clipboard More',
  'Clipboard Paste',
  'Clipboard Pulse',
  'Clipboard Search',
  'Clipboard Settings',
  'Clipboard Task',
  'Clipboard Task Add',
  'Clipboard Task List Ltr',
  'Clipboard Task List Rtl',
  'Clipboard Text Ltr',
  'Clipboard Text Rtl',
  'Clock',
  'Clock Alarm',
  'Clock Arrow Download',
  'Clock Dismiss',
  'Closed Caption',
  'Closed Caption Off',
  'Cloud',
  'Cloud Arrow Down',
  'Cloud Arrow Up',
  'Cloud Backup',
  'Cloud Checkmark',
  'Cloud Dismiss',
  'Cloud Download',
  'Cloud Flow',
  'Cloud Off',
  'Cloud Offline',
  'Cloud Swap',
  'Cloud Sync',
  'Cloud Sync Complete',
  'Cloud Words',
  'Code',
  'Collections',
  'Collections Add',
  'Color',
  'Color Background',
  'Color Fill',
  'Color Line',
  'Column Edit',
  'Column Triple',
  'Column Triple Edit',
  'Comma',
  'Comment',
  'Comment Add',
  'Comment Arrow Left',
  'Comment Arrow Right',
  'Comment Checkmark',
  'Comment Dismiss',
  'Comment Edit',
  'Comment Lightning',
  'Comment Mention',
  'Comment Multiple',
  'Comment Multiple Checkmark',
  'Comment Note',
  'Comment Off',
  'Communication',
  'Communication Person',
  'Compass Northwest',
  'Component2 Double Tap Swipe Down',
  'Component2 Double Tap Swipe Up',
  'Compose',
  'Conference Room',
  'Connector',
  'Contact Card',
  'Contact Card Group',
  'Content Settings',
  'Contract Down Left',
  'Control Button',
  'Convert Range',
  'Convert To Table',
  'Convert To Text',
  'Convert To Type',
  'Cookies',
  'Copy',
  'Copy Add',
  'Copy Arrow Right',
  'Couch',
  'Credit Card Person',
  'Credit Card Toolbox',
  'Crop',
  'Crop Interim',
  'Crop Interim Off',
  'Cube',
  'Cube Sync',
  'Currency Dollar Euro',
  'Currency Dollar Rupee',
  'Cursor',
  'Cursor Click',
  'Cursor Hover',
  'Cursor Hover Off',
  'Cut',
  'Dark Theme',
  'Data Area',
  'Data Bar Horizontal',
  'Data Bar Vertical',
  'Data Bar Vertical Add',
  'Data Funnel',
  'Data Histogram',
  'Data Line',
  'Data Pie',
  'Data Scatter',
  'Data Sunburst',
  'Data Treemap',
  'Data Trending',
  'Data Usage',
  'Data Usage Edit',
  'Data Waterfall',
  'Data Whisker',
  'Database',
  'Database Link',
  'Database Search',
  'Decimal Arrow Left',
  'Decimal Arrow Right',
  'Delete',
  'Delete Dismiss',
  'Delete Off',
  'Dentist',
  'Design Ideas',
  'Desktop',
  'Desktop Arrow Right',
  'Desktop Keyboard',
  'Desktop Pulse',
  'Desktop Speaker',
  'Desktop Speaker Off',
  'Developer Board',
  'Device Eq',
  'Device Meeting Room',
  'Device Meeting Room Remote',
  'Diagram',
  'Dialpad',
  'Dialpad Off',
  'Directions',
  'Dismiss',
  'Dismiss Circle',
  'Dismiss Square',
  'Diversity',
  'Divider Short',
  'Divider Tall',
  'Dock',
  'Dock Panel Left',
  'Dock Panel Right',
  'Dock Row',
  'Doctor',
  'Document',
  'Document Add',
  'Document Arrow Left',
  'Document Arrow Right',
  'Document Briefcase',
  'Document Bullet List',
  'Document Bullet List Clock',
  'Document Bullet List Off',
  'Document Catch Up',
  'Document Checkmark',
  'Document Chevron Double',
  'Document Copy',
  'Document Css',
  'Document Dismiss',
  'Document Edit',
  'Document Endnote',
  'Document Error',
  'Document Footer',
  'Document Footer Dismiss',
  'Document Footer Remove',
  'Document Header',
  'Document Header Dismiss',
  'Document Header Footer',
  'Document Header Remove',
  'Document Heart',
  'Document Heart Pulse',
  'Document Javascript',
  'Document Landscape',
  'Document Landscape Data',
  'Document Link',
  'Document Margins',
  'Document Multiple',
  'Document Multiple Percent',
  'Document Multiple Prohibited',
  'Document One Page',
  'Document Page Bottom Center',
  'Document Page Bottom Left',
  'Document Page Bottom Right',
  'Document Page Break',
  'Document Page Number',
  'Document Page Top Center',
  'Document Page Top Left',
  'Document Page Top Right',
  'Document Pdf',
  'Document Percent',
  'Document Pill',
  'Document Prohibited',
  'Document Question Mark',
  'Document Ribbon',
  'Document Save',
  'Document Search',
  'Document Split Hint',
  'Document Split Hint Off',
  'Document Sync',
  'Document Table',
  'Document Text',
  'Document Text Link',
  'Document Toolbox',
  'Document Width',
  'Door Arrow Left',
  'Door Tag',
  'Double Swipe Down',
  'Double Swipe Up',
  'Drafts',
  'Drag',
  'Draw Shape',
  'Draw Text',
  'Drink Beer',
  'Drink Coffee',
  'Drink Margarita',
  'Drink To Go',
  'Drink Wine',
  'Drive Train',
  'Drop',
  'Dual Screen',
  'Dual Screen Add',
  'Dual Screen Arrow Right',
  'Dual Screen Arrow Up',
  'Dual Screen Clock',
  'Dual Screen Closed Alert',
  'Dual Screen Desktop',
  'Dual Screen Dismiss',
  'Dual Screen Group',
  'Dual Screen Header',
  'Dual Screen Lock',
  'Dual Screen Mirror',
  'Dual Screen Pagination',
  'Dual Screen Settings',
  'Dual Screen Span',
  'Dual Screen Speaker',
  'Dual Screen Status Bar',
  'Dual Screen Tablet',
  'Dual Screen Update',
  'Dual Screen Vertical Scroll',
  'Dual Screen Vibrate',
  'Dumbbell',
  'Earth',
  'Edit',
  'Edit Off',
  'Edit Settings',
  'Emoji',
  'Emoji Add',
  'Emoji Angry',
  'Emoji Hand',
  'Emoji Laugh',
  'Emoji Meh',
  'Emoji Multiple',
  'Emoji Sad',
  'Emoji Surprise',
  'Engine',
  'Equal Off',
  'Eraser',
  'Eraser Medium',
  'Eraser Segment',
  'Eraser Small',
  'Eraser Tool',
  'Error Circle',
  'Expand Up Left',
  'Expand Up Right',
  'Extended Dock',
  'Extension',
  'Eye Hide',
  'Eye Show',
  'Eye Tracking Off',
  'Eye Tracking On',
  'Eyedropper',
  'F Stop',
  'Fast Acceleration',
  'Fast Forward',
  'Filter',
  'Filter Dismiss',
  'Filter Sync',
  'Fingerprint',
  'Fixed Width',
  'Flag',
  'Flag Off',
  'Flag Pride',
  'Flash Auto',
  'Flash Checkmark',
  'Flash Off',
  'Flash On',
  'Flashlight',
  'Flashlight Off',
  'Flip Horizontal',
  'Flip Vertical',
  'Fluid',
  'Folder',
  'Folder Add',
  'Folder Arrow Right',
  'Folder Arrow Up',
  'Folder Link',
  'Folder Open',
  'Folder Prohibited',
  'Folder Swap',
  'Folder Zip',
  'Font Decrease',
  'Font Increase',
  'Font Space Tracking In',
  'Font Space Tracking Out',
  'Food',
  'Food Cake',
  'Food Egg',
  'Food Pizza',
  'Food Toast',
  'Form New',
  'Fps120',
  'Fps',
  'Fps',
  'Fps30',
  'Fps60',
  'Fps960',
  'Full Screen Maximize',
  'Full Screen Minimize',
  'Games',
  'Gantt Chart',
  'Gas',
  'Gas Pump',
  'Gauge',
  'Gavel',
  'Gesture',
  'Gif',
  'Gift',
  'Gift Card Add',
  'Glance',
  'Glasses',
  'Glasses Off',
  'Globe',
  'Globe Add',
  'Globe Clock',
  'Globe Desktop',
  'Globe Location',
  'Globe Person',
  'Globe Search',
  'Globe Shield',
  'Globe Surface',
  'Globe Video',
  'Grid',
  'Grid Dots',
  'Group',
  'Group Dismiss',
  'Group List',
  'Group Return',
  'Guardian',
  'Guest',
  'Guest Add',
  'Guitar',
  'Hand Draw',
  'Hand Left',
  'Hand Right',
  'Handshake',
  'Hat Graduation',
  'Hd',
  'Hdr',
  'Headphones',
  'Headphones Sound Wave',
  'Headset',
  'Headset Add',
  'Headset Vr',
  'Heart',
  'Heart Pulse',
  'Highlight',
  'Highlight Accent',
  'History',
  'Home',
  'Home Add',
  'Home Checkmark',
  'Home Person',
  'Icons',
  'Image',
  'Image Add',
  'Image Alt Text',
  'Image Arrow Back',
  'Image Arrow Counterclockwise',
  'Image Arrow Forward',
  'Image Copy',
  'Image Edit',
  'Image Globe',
  'Image Multiple',
  'Image Off',
  'Image Prohibited',
  'Image Reflection',
  'Image Search',
  'Image Shadow',
  'Immersive Reader',
  'Important',
  'Incognito',
  'Info',
  'Ink Stroke',
  'Inking Tool',
  'Inking Tool Accent',
  'Inprivate Account',
  'Ios Arrow Left',
  'Ios Arrow Ltr',
  'Ios Arrow Right',
  'Ios Arrow Rtl',
  'Iot',
  'Javascript',
  'Key',
  'Keyboard123',
  'Keyboard',
  'Keyboard Dock',
  'Keyboard Layout Float',
  'Keyboard Layout One Handed Left',
  'Keyboard Layout Resize',
  'Keyboard Layout Split',
  'Keyboard Shift',
  'Keyboard Shift Uppercase',
  'Keyboard Tab',
  'Laptop',
  'Lasso',
  'Launcher Settings',
  'Layer',
  'Leaf One',
  'Leaf Three',
  'Leaf Two',
  'Learning App',
  'Library',
  'Lightbulb',
  'Lightbulb Circle',
  'Lightbulb Filament',
  'Likert',
  'Line Style',
  'Link',
  'Link Dismiss',
  'Link Edit',
  'Link Square',
  'List',
  'Live',
  'Live Off',
  'Local Language',
  'Local Language Zi',
  'Location',
  'Location Dismiss',
  'Location Live',
  'Location Off',
  'Lock Closed',
  'Lock Multiple',
  'Lock Open',
  'Lock Shield',
  'Lottery',
  'Luggage',
  'Mail',
  'Mail Add',
  'Mail Alert',
  'Mail All',
  'Mail Arrow Up',
  'Mail Clock',
  'Mail Copy',
  'Mail Dismiss',
  'Mail Error',
  'Mail Inbox',
  'Mail Inbox Add',
  'Mail Inbox All',
  'Mail Inbox Arrow Right',
  'Mail Inbox Arrow Up',
  'Mail Inbox Checkmark',
  'Mail Inbox Dismiss',
  'Mail Link',
  'Mail Multiple',
  'Mail Off',
  'Mail Prohibited',
  'Mail Read',
  'Mail Template',
  'Mail Unread',
  'Map',
  'Map Drive',
  'Match App Layout',
  'Math Format Linear',
  'Math Format Professional',
  'Math Formula',
  'Maximize',
  'Meet Now',
  'Megaphone',
  'Megaphone Off',
  'Mention',
  'Merge',
  'Mic Off',
  'Mic On',
  'Mic Prohibited',
  'Mic Settings',
  'Mic Sparkle',
  'Microscope',
  'Midi',
  'Mobile Optimized',
  'Molecule',
  'Money',
  'Money Calculator',
  'More Horizontal',
  'More Vertical',
  'Movies And Tv',
  'Multiplier12x',
  'Multiplier15x',
  'Multiplier18x',
  'Multiplier1x',
  'Multiplier2x',
  'Multiplier5x',
  'Multiselect',
  'Music Note1',
  'Music Note2',
  'My Location',
  'Navigation',
  'Navigation Unread',
  'Network Check',
  'New',
  'News',
  'Next',
  'Note',
  'Note Add',
  'Note Edit',
  'Notebook',
  'Notebook Add',
  'Notebook Error',
  'Notebook Lightning',
  'Notebook Question Mark',
  'Notebook Section',
  'Notebook Section Arrow Right',
  'Notebook Subsection',
  'Notebook Sync',
  'Notepad',
  'Notepad Person',
  'Number Row',
  'Number Symbol',
  'Number Symbol Dismiss',
  'Number Symbol Square',
  'Office Apps',
  'Open',
  'Open Folder',
  'Open Off',
  'Options',
  'Organization',
  'Orientation',
  'Padding Down',
  'Padding Left',
  'Padding Right',
  'Padding Top',
  'Page Fit',
  'Paint Brush',
  'Paint Brush Arrow Down',
  'Paint Brush Arrow Up',
  'Paint Bucket',
  'Pair',
  'Pane Close',
  'Pane Open',
  'Panel Left',
  'Panel Right',
  'Panel Right Contract',
  'Panel Right Expand',
  'Password',
  'Patch',
  'Patient',
  'Pause',
  'Pause Circle',
  'Payment',
  'People',
  'People Add',
  'People Audience',
  'People Checkmark',
  'People Community',
  'People Community Add',
  'People Error',
  'People Money',
  'People Search',
  'People Settings',
  'People Swap',
  'People Team',
  'People Team Add',
  'People Team Delete',
  'People Team Toolbox',
  'Person',
  'Person Accounts',
  'Person Add',
  'Person Arrow Left',
  'Person Arrow Right',
  'Person Available',
  'Person Board',
  'Person Call',
  'Person Chat',
  'Person Clock',
  'Person Delete',
  'Person Feedback',
  'Person Lock',
  'Person Mail',
  'Person Money',
  'Person Note',
  'Person Pill',
  'Person Prohibited',
  'Person Question Mark',
  'Person Support',
  'Person Swap',
  'Person Voice',
  'Phone',
  'Phone Add',
  'Phone Arrow Right',
  'Phone Desktop',
  'Phone Dismiss',
  'Phone Laptop',
  'Phone Link Setup',
  'Phone Lock',
  'Phone Page Header',
  'Phone Pagination',
  'Phone Screen Time',
  'Phone Shake',
  'Phone Span In',
  'Phone Span Out',
  'Phone Speaker',
  'Phone Status Bar',
  'Phone Tablet',
  'Phone Update',
  'Phone Vertical Scroll',
  'Phone Vibrate',
  'Photo Filter',
  'Pi',
  'Picture In Picture',
  'Pill',
  'Pin',
  'Pin Off',
  'Pivot',
  'Play',
  'Play Circle',
  'Plug Disconnected',
  'Point Scan',
  'Poll',
  'Port Hdmi',
  'Port Micro Usb',
  'Port Usb A',
  'Port Usb C',
  'Position Backward',
  'Position Forward',
  'Position To Back',
  'Position To Front',
  'Power',
  'Predictions',
  'Premium',
  'Premium Person',
  'Presenter',
  'Presenter Off',
  'Preview Link',
  'Previous',
  'Print',
  'Print Add',
  'Production',
  'Production Checkmark',
  'Prohibited',
  'Prohibited Multiple',
  'Projection Screen',
  'Projection Screen Dismiss',
  'Protocol Handler',
  'Pulse',
  'Pulse Square',
  'Puzzle Cube',
  'Puzzle Piece',
  'Qr Code',
  'Question',
  'Question Circle',
  'Quiz New',
  'Radio Button',
  'Rating Mature',
  'Ratio One To One',
  'Re Order',
  'Re Order Dots Horizontal',
  'Re Order Dots Vertical',
  'Read Aloud',
  'Reading List',
  'Reading List Add',
  'Reading Mode Mobile',
  'Real Estate',
  'Receipt',
  'Receipt Add',
  'Receipt Bag',
  'Receipt Cube',
  'Receipt Money',
  'Receipt Play',
  'Record',
  'Record Stop',
  'Rectangle Landscape',
  'Rename',
  'Resize Image',
  'Resize Large',
  'Resize Small',
  'Resize Table',
  'Resize Video',
  'Reward',
  'Rewind',
  'Ribbon',
  'Ribbon Add',
  'Ribbon Star',
  'Road Cone',
  'Rocket',
  'Rotate Left',
  'Rotate Right',
  'Router',
  'Row Triple',
  'Rss',
  'Ruler',
  'Run',
  'Save',
  'Save Arrow Right',
  'Save Copy',
  'Save Edit',
  'Savings',
  'Scale Fill',
  'Scale Fit',
  'Scales',
  'Scan',
  'Scan Object',
  'Scan Table',
  'Scan Text',
  'Scan Thumb Up',
  'Scan Thumb Up Off',
  'Scan Type',
  'Scratchpad',
  'Screenshot',
  'Search',
  'Search Info',
  'Search Square',
  'Search Visual',
  'Select All Off',
  'Select All On',
  'Select Object',
  'Send',
  'Send Clock',
  'Send Copy',
  'Serial Port',
  'Server',
  'Service Bell',
  'Set Top Stack',
  'Settings',
  'Shape Exclude',
  'Shape Intersect',
  'Shape Subtract',
  'Shape Union',
  'Shapes',
  'Share',
  'Share Android',
  'Share Close Tray',
  'Share Ios',
  'Share Screen Person',
  'Share Screen Person Overlay',
  'Share Screen Person Overlay Inside',
  'Share Screen Start',
  'Share Screen Stop',
  'Shield',
  'Shield Badge',
  'Shield Checkmark',
  'Shield Dismiss',
  'Shield Error',
  'Shield Keyhole',
  'Shield Prohibited',
  'Shield Task',
  'Shield Video',
  'Shifts',
  'Shifts30 Minutes',
  'Shifts Activity',
  'Shifts Add',
  'Shifts Availability',
  'Shifts Checkmark',
  'Shifts Day',
  'Shifts Open',
  'Shifts Prohibited',
  'Shifts Question Mark',
  'Shifts Team',
  'Shopping Bag',
  'Shortpick',
  'Sign Out',
  'Signature',
  'Signed',
  'Sim',
  'Skip Backward10',
  'Skip Forward10',
  'Skip Forward30',
  'Skip Forward Tab',
  'Sleep',
  'Slide Add',
  'Slide Design',
  'Slide Eraser',
  'Slide Grid',
  'Slide Hide',
  'Slide Layout',
  'Slide Microphone',
  'Slide Multiple',
  'Slide Multiple Arrow Right',
  'Slide Multiple Search',
  'Slide Search',
  'Slide Settings',
  'Slide Size',
  'Slide Text',
  'Slide Transition',
  'Smartwatch',
  'Smartwatch Dot',
  'Snooze',
  'Sound Source',
  'Spacebar',
  'Sparkle',
  'Speaker0',
  'Speaker1',
  'Speaker2',
  'Speaker Bluetooth',
  'Speaker Edit',
  'Speaker Mute',
  'Speaker Off',
  'Speaker Settings',
  'Speaker Usb',
  'Split Horizontal',
  'Split Vertical',
  'Sport',
  'Sport American Football',
  'Sport Baseball',
  'Sport Basketball',
  'Sport Hockey',
  'Sport Soccer',
  'Square Arrow Forward',
  'Square Multiple',
  'Stack',
  'Stack Star',
  'Star',
  'Star Add',
  'Star Arrow Right End',
  'Star Arrow Right Start',
  'Star Edit',
  'Star Emphasis',
  'Star Half',
  'Star Line Horizontal3',
  'Star Off',
  'Star One Quarter',
  'Star Prohibited',
  'Star Settings',
  'Star Three Quarter',
  'Status',
  'Steps',
  'Stethoscope',
  'Sticker',
  'Sticker Add',
  'Stop',
  'Storage',
  'Store Microsoft',
  'Stream',
  'Strikethrough Ga Na',
  'Style Guide',
  'Sub Grid',
  'Subtract',
  'Subtract Circle',
  'Subtract Square',
  'Surface Earbuds',
  'Surface Hub',
  'Swipe Down',
  'Swipe Right',
  'Swipe Up',
  'Symbols',
  'Syringe',
  'System',
  'Tab',
  'Tab Add',
  'Tab Arrow Left',
  'Tab Desktop Arrow Clockwise',
  'Tab Desktop Bottom',
  'Tab Desktop Image',
  'Tab Desktop Multiple Bottom',
  'Tab In Private',
  'Tab Inprivate Account',
  'Tab Prohibited',
  'Tab Shield Dismiss',
  'Table',
  'Table Add',
  'Table Cell Edit',
  'Table Cells Merge',
  'Table Cells Split',
  'Table Delete Column',
  'Table Delete Row',
  'Table Dismiss',
  'Table Edit',
  'Table Freeze Column',
  'Table Freeze Column And Row',
  'Table Freeze Row',
  'Table Insert Column',
  'Table Insert Row',
  'Table Move Above',
  'Table Move Below',
  'Table Move Left',
  'Table Move Right',
  'Table Resize Column',
  'Table Resize Row',
  'Table Settings',
  'Table Simple',
  'Table Stack Above',
  'Table Stack Below',
  'Table Stack Left',
  'Table Stack Right',
  'Table Switch',
  'Tablet',
  'Tablet Speaker',
  'Tabs',
  'Tag',
  'Tag Dismiss',
  'Tag Lock',
  'Tag Lock Accent',
  'Tag Question Mark',
  'Tap Double',
  'Tap Single',
  'Target',
  'Target Arrow',
  'Target Edit',
  'Task List Add',
  'Task List Ltr',
  'Task List Rtl',
  'Task List Square Add',
  'Task List Square Ltr',
  'Task List Square Rtl',
  'Tasks App',
  'Teddy',
  'Temperature',
  'Tent',
  'Tetris App',
  'Text',
  'Text Add',
  'Text Add Space After',
  'Text Add Space Before',
  'Text Add T',
  'Text Align Center',
  'Text Align Center Rotate270',
  'Text Align Distributed',
  'Text Align Distributed Evenly',
  'Text Align Distributed Vertical',
  'Text Align Justify',
  'Text Align Justify Low',
  'Text Align Justify Low Rotate90',
  'Text Align Justify Rotate90',
  'Text Align Left',
  'Text Align Left Rotate270',
  'Text Align Right',
  'Text Align Right Rotate270',
  'Text Bold',
  'Text Bullet List Add',
  'Text Bullet List Ltr',
  'Text Bullet List Rtl',
  'Text Bullet List Square',
  'Text Bullet List Square Edit',
  'Text Bullet List Square Warning',
  'Text Bullet List Tree',
  'Text Case Lowercase',
  'Text Case Title',
  'Text Case Uppercase',
  'Text Change Case',
  'Text Clear Formatting',
  'Text Clear Formatting Ga',
  'Text Collapse',
  'Text Color',
  'Text Color Accent',
  'Text Color Ga',
  'Text Column One',
  'Text Column One Narrow',
  'Text Column One Wide',
  'Text Column Three',
  'Text Column Two',
  'Text Column Two Left',
  'Text Column Two Right',
  'Text Continuous',
  'Text Description',
  'Text Direction Horizontal Left',
  'Text Direction Horizontal Ltr',
  'Text Direction Horizontal Right',
  'Text Direction Horizontal Rtl',
  'Text Direction Rotate270 Ltr',
  'Text Direction Rotate270 Right',
  'Text Direction Rotate90 Left',
  'Text Direction Rotate90 Ltr',
  'Text Direction Rotate90 Right',
  'Text Direction Rotate90 Rtl',
  'Text Direction Vertical',
  'Text Edit Style',
  'Text Edit Style Ga',
  'Text Effects',
  'Text Effects Ga',
  'Text Expand',
  'Text Field',
  'Text First Line',
  'Text Font',
  'Text Font Size',
  'Text Footnote',
  'Text Footnote Ga Na',
  'Text Grammar Arrow Left',
  'Text Grammar Arrow Right',
  'Text Grammar Checkmark',
  'Text Grammar Dismiss',
  'Text Grammar Settings',
  'Text Grammar Wand',
  'Text Hanging',
  'Text Header1',
  'Text Header2',
  'Text Header3',
  'Text Indent Decrease',
  'Text Indent Decrease Ltr',
  'Text Indent Decrease Rtl',
  'Text Indent Increase',
  'Text Indent Increase Ltr',
  'Text Indent Increase Rtl',
  'Text Italic',
  'Text Line Spacing',
  'Text More',
  'Text Number Format',
  'Text Number Format Ga Na Da',
  'Text Number List Ltr',
  'Text Number List Rtl',
  'Text Paragraph',
  'Text Paragraph Direction',
  'Text Position Behind',
  'Text Position Front',
  'Text Position Line',
  'Text Position Square',
  'Text Position Through',
  'Text Position Tight',
  'Text Position Top Bottom',
  'Text Proofing Tools',
  'Text Proofing Tools Ga Na Da',
  'Text Proofing Tools Zi',
  'Text Quote',
  'Text Sort Ascending',
  'Text Sort Descending',
  'Text Strikethrough',
  'Text Strikethrough S',
  'Text Subscript',
  'Text Superscript',
  'Text T',
  'Text Underline',
  'Text Word Count',
  'Text Wrap',
  'Textbox',
  'Textbox Align Bottom',
  'Textbox Align Bottom Rotate90',
  'Textbox Align Center',
  'Textbox Align Middle',
  'Textbox Align Middle Rotate90',
  'Textbox Align Top',
  'Textbox Align Top Rotate90',
  'Textbox More',
  'Textbox Vertical',
  'Thinking',
  'Thumb Dislike',
  'Thumb Like',
  'Ticket Diagonal',
  'Ticket Horizontal',
  'Time And Weather',
  'Time Picker',
  'Timeline',
  'Timer10',
  'Timer',
  'Timer2',
  'Timer3',
  'Timer Off',
  'Toggle Left',
  'Toggle Right',
  'Toolbox',
  'Tooltip Quote',
  'Top Speed',
  'Translate',
  'Transmission',
  'Trophy',
  'Tv',
  'Tv Usb',
  'Umbrella',
  'Uninstall App',
  'Usb Plug',
  'Usb Port',
  'Usb Stick',
  'Vault',
  'Vehicle Bicycle',
  'Vehicle Bus',
  'Vehicle Cab',
  'Vehicle Car',
  'Vehicle Car Collision',
  'Vehicle Ship',
  'Vehicle Subway',
  'Vehicle Truck',
  'Vehicle Truck Profile',
  'Video',
  'Video360',
  'Video Add',
  'Video Background Effect',
  'Video Clip',
  'Video Off',
  'Video Person',
  'Video Person Call',
  'Video Person Off',
  'Video Person Sparkle',
  'Video Person Star',
  'Video Person Star Off',
  'Video Play Pause',
  'Video Prohibited',
  'Video Security',
  'Video Switch',
  'View Desktop',
  'View Desktop Mobile',
  'Voicemail',
  'Vote',
  'Walkie Talkie',
  'Wallet',
  'Wallpaper',
  'Wand',
  'Warning',
  'Weather Blowing Snow',
  'Weather Cloudy',
  'Weather Drizzle',
  'Weather Duststorm',
  'Weather Fog',
  'Weather Hail Day',
  'Weather Hail Night',
  'Weather Haze',
  'Weather Moon',
  'Weather Moon Off',
  'Weather Partly Cloudy Day',
  'Weather Partly Cloudy Night',
  'Weather Rain',
  'Weather Rain Showers Day',
  'Weather Rain Showers Night',
  'Weather Rain Snow',
  'Weather Snow',
  'Weather Snow Shower Day',
  'Weather Snow Shower Night',
  'Weather Snowflake',
  'Weather Squalls',
  'Weather Sunny',
  'Weather Sunny High',
  'Weather Sunny Low',
  'Weather Thunderstorm',
  'Web Asset',
  'Whiteboard',
  'Wifi1',
  'Wifi2',
  'Wifi3',
  'Wifi4',
  'Wifi Lock',
  'Wifi Off',
  'Wifi Protected',
  'Wifi Warning',
  'Window',
  'Window Arrow Up',
  'Window Dev Tools',
  'Window New',
  'Window Shield',
  'Wrench',
  'Xbox Console',
  'Xray',
  'Zoom In',
  'Zoom Out',
  
  
];

var fileName = [
  'ic_fluent_access_time_24_filled',
  'ic_fluent_accessibility_24_filled',
  'ic_fluent_accessibility_checkmark_24_filled',
  'ic_fluent_add_24_filled',
  'ic_fluent_add_circle_24_filled',
  'ic_fluent_add_square_24_filled',
  'ic_fluent_add_subtract_circle_24_filled',
  'ic_fluent_airplane_24_filled',
  'ic_fluent_airplane_take_off_24_filled',
  'ic_fluent_album_24_filled',
  'ic_fluent_album_add_24_filled',
  'ic_fluent_alert_24_filled',
  'ic_fluent_alert_off_24_filled',
  'ic_fluent_alert_on_24_filled',
  'ic_fluent_alert_snooze_24_filled',
  'ic_fluent_alert_urgent_24_filled',
  'ic_fluent_align_bottom_24_filled',
  'ic_fluent_align_center_horizontal_24_filled',
  'ic_fluent_align_center_vertical_24_filled',
  'ic_fluent_align_left_24_filled',
  'ic_fluent_align_right_24_filled',
  'ic_fluent_align_top_24_filled',
  'ic_fluent_animal_cat_24_filled',
  'ic_fluent_animal_dog_24_filled',
  'ic_fluent_animal_rabbit_24_filled',
  'ic_fluent_animal_turtle_24_filled',
  'ic_fluent_app_folder_24_filled',
  'ic_fluent_app_generic_24_filled',
  'ic_fluent_app_recent_24_filled',
  'ic_fluent_app_store_24_filled',
  'ic_fluent_app_title_24_filled',
  'ic_fluent_approvals_app_24_filled',
  'ic_fluent_apps_24_filled',
  'ic_fluent_apps_add_in_24_filled',
  'ic_fluent_apps_list_24_filled',
  'ic_fluent_apps_list_detail_24_filled',
  'ic_fluent_archive_24_filled',
  'ic_fluent_arrow_autofit_content_24_filled',
  'ic_fluent_arrow_autofit_down_24_filled',
  'ic_fluent_arrow_autofit_height_24_filled',
  'ic_fluent_arrow_autofit_height_dotted_24_filled',
  'ic_fluent_arrow_autofit_up_24_filled',
  'ic_fluent_arrow_autofit_width_24_filled',
  'ic_fluent_arrow_autofit_width_dotted_24_filled',
  'ic_fluent_arrow_bidirectional_up_down_24_filled',
  'ic_fluent_arrow_bounce_24_filled',
  'ic_fluent_arrow_circle_down_24_filled',
  'ic_fluent_arrow_circle_down_double_24_filled',
  'ic_fluent_arrow_circle_down_right_24_filled',
  'ic_fluent_arrow_circle_down_split_24_filled',
  'ic_fluent_arrow_circle_left_24_filled',
  'ic_fluent_arrow_circle_right_24_filled',
  'ic_fluent_arrow_circle_up_24_filled',
  'ic_fluent_arrow_circle_up_left_24_filled',
  'ic_fluent_arrow_clockwise_24_filled',
  'ic_fluent_arrow_clockwise_dashes_24_filled',
  'ic_fluent_arrow_collapse_all_24_filled',
  'ic_fluent_arrow_counterclockwise_24_filled',
  'ic_fluent_arrow_counterclockwise_dashes_24_filled',
  'ic_fluent_arrow_curve_down_left_24_filled',
  'ic_fluent_arrow_down_24_filled',
  'ic_fluent_arrow_down_left_24_filled',
  'ic_fluent_arrow_download_24_filled',
  'ic_fluent_arrow_enter_left_24_filled',
  'ic_fluent_arrow_enter_up_24_filled',
  'ic_fluent_arrow_expand_24_filled',
  'ic_fluent_arrow_export_ltr_24_filled',
  'ic_fluent_arrow_export_up_24_filled',
  'ic_fluent_arrow_forward_24_filled',
  'ic_fluent_arrow_growth_24_filled',
  'ic_fluent_arrow_hook_down_left_24_filled',
  'ic_fluent_arrow_hook_down_right_24_filled',
  'ic_fluent_arrow_hook_up_left_24_filled',
  'ic_fluent_arrow_hook_up_right_24_filled',
  'ic_fluent_arrow_import_24_filled',
  'ic_fluent_arrow_left_24_filled',
  'ic_fluent_arrow_maximize_24_filled',
  'ic_fluent_arrow_maximize_vertical_24_filled',
  'ic_fluent_arrow_minimize_24_filled',
  'ic_fluent_arrow_minimize_vertical_24_filled',
  'ic_fluent_arrow_move_24_filled',
  'ic_fluent_arrow_next_24_filled',
  'ic_fluent_arrow_previous_24_filled',
  'ic_fluent_arrow_redo_24_filled',
  'ic_fluent_arrow_repeat_all_24_filled',
  'ic_fluent_arrow_repeat_all_off_24_filled',
  'ic_fluent_arrow_reply_24_filled',
  'ic_fluent_arrow_reply_all_24_filled',
  'ic_fluent_arrow_reply_down_24_filled',
  'ic_fluent_arrow_reset_24_filled',
  'ic_fluent_arrow_right_24_filled',
  'ic_fluent_arrow_rotate_clockwise_24_filled',
  'ic_fluent_arrow_rotate_counterclockwise_24_filled',
  'ic_fluent_arrow_routing_24_filled',
  'ic_fluent_arrow_routing_rectangle_multiple_24_filled',
  'ic_fluent_arrow_sort_24_filled',
  'ic_fluent_arrow_sort_down_24_filled',
  'ic_fluent_arrow_sort_up_24_filled',
  'ic_fluent_arrow_square_down_24_filled',
  'ic_fluent_arrow_swap_24_filled',
  'ic_fluent_arrow_sync_24_filled',
  'ic_fluent_arrow_sync_circle_24_filled',
  'ic_fluent_arrow_trending_24_filled',
  'ic_fluent_arrow_trending_checkmark_24_filled',
  'ic_fluent_arrow_trending_lines_24_filled',
  'ic_fluent_arrow_trending_settings_24_filled',
  'ic_fluent_arrow_turn_bidirectional_down_right_24_filled',
  'ic_fluent_arrow_turn_right_24_filled',
  'ic_fluent_arrow_undo_24_filled',
  'ic_fluent_arrow_up_24_filled',
  'ic_fluent_arrow_up_left_24_filled',
  'ic_fluent_arrow_up_right_24_filled',
  'ic_fluent_arrow_upload_24_filled',
  'ic_fluent_arrows_bidirectional_24_filled',
  'ic_fluent_attach_24_filled',
  'ic_fluent_attach_arrow_right_24_filled',
  'ic_fluent_attach_text_24_filled',
  'ic_fluent_auto_fit_height_24_filled',
  'ic_fluent_auto_fit_width_24_filled',
  'ic_fluent_autocorrect_24_filled',
  'ic_fluent_autofit_content_24_filled',
  'ic_fluent_autosum_24_filled',
  'ic_fluent_backpack_24_filled',
  'ic_fluent_backpack_add_24_filled',
  'ic_fluent_backspace_24_filled',
  'ic_fluent_badge_24_filled',
  'ic_fluent_balloon_24_filled',
  'ic_fluent_barcode_scanner_24_filled',
  'ic_fluent_battery_0_24_filled',
  'ic_fluent_battery_1_24_filled',
  'ic_fluent_battery_2_24_filled',
  'ic_fluent_battery_3_24_filled',
  'ic_fluent_battery_4_24_filled',
  'ic_fluent_battery_5_24_filled',
  'ic_fluent_battery_6_24_filled',
  'ic_fluent_battery_7_24_filled',
  'ic_fluent_battery_8_24_filled',
  'ic_fluent_battery_9_24_filled',
  'ic_fluent_battery_charge_24_filled',
  'ic_fluent_battery_checkmark_24_filled',
  'ic_fluent_battery_full_24_filled',
  'ic_fluent_battery_saver_24_filled',
  'ic_fluent_battery_warning_24_filled',
  'ic_fluent_beach_24_filled',
  'ic_fluent_beaker_24_filled',
  'ic_fluent_beaker_edit_24_filled',
  'ic_fluent_bed_24_filled',
  'ic_fluent_bin_full_24_filled',
  'ic_fluent_block_24_filled',
  'ic_fluent_bluetooth_24_filled',
  'ic_fluent_bluetooth_connected_24_filled',
  'ic_fluent_bluetooth_disabled_24_filled',
  'ic_fluent_bluetooth_searching_24_filled',
  'ic_fluent_blur_24_filled',
  'ic_fluent_board_24_filled',
  'ic_fluent_board_split_24_filled',
  'ic_fluent_book_24_filled',
  'ic_fluent_book_add_24_filled',
  'ic_fluent_book_clock_24_filled',
  'ic_fluent_book_coins_24_filled',
  'ic_fluent_book_compass_24_filled',
  'ic_fluent_book_contacts_24_filled',
  'ic_fluent_book_database_24_filled',
  'ic_fluent_book_exclamation_mark_24_filled',
  'ic_fluent_book_globe_24_filled',
  'ic_fluent_book_information_24_filled',
  'ic_fluent_book_letter_24_filled',
  'ic_fluent_book_number_24_filled',
  'ic_fluent_book_open_24_filled',
  'ic_fluent_book_open_globe_24_filled',
  'ic_fluent_book_open_microphone_24_filled',
  'ic_fluent_book_pulse_24_filled',
  'ic_fluent_book_question_mark_24_filled',
  'ic_fluent_book_question_mark_rtl_24_filled',
  'ic_fluent_book_search_24_filled',
  'ic_fluent_book_star_24_filled',
  'ic_fluent_book_theta_24_filled',
  'ic_fluent_book_toolbox_24_filled',
  'ic_fluent_bookmark_24_filled',
  'ic_fluent_bookmark_add_24_filled',
  'ic_fluent_bookmark_multiple_24_filled',
  'ic_fluent_bookmark_off_24_filled',
  'ic_fluent_border_24_filled',
  'ic_fluent_border_all_24_filled',
  'ic_fluent_border_bottom_24_filled',
  'ic_fluent_border_bottom_double_24_filled',
  'ic_fluent_border_bottom_thick_24_filled',
  'ic_fluent_border_left_24_filled',
  'ic_fluent_border_outside_24_filled',
  'ic_fluent_border_outside_thick_24_filled',
  'ic_fluent_border_right_24_filled',
  'ic_fluent_border_top_24_filled',
  'ic_fluent_border_top_bottom_24_filled',
  'ic_fluent_border_top_bottom_double_24_filled',
  'ic_fluent_border_top_bottom_thick_24_filled',
  'ic_fluent_bot_24_filled',
  'ic_fluent_bot_add_24_filled',
  'ic_fluent_bowl_chopsticks_24_filled',
  'ic_fluent_box_edit_24_filled',
  'ic_fluent_box_toolbox_24_filled',
  'ic_fluent_braces_variable_24_filled',
  'ic_fluent_brain_circuit_24_filled',
  'ic_fluent_branch_24_filled',
  'ic_fluent_branch_compare_24_filled',
  'ic_fluent_branch_fork_24_filled',
  'ic_fluent_briefcase_24_filled',
  'ic_fluent_briefcase_medical_24_filled',
  'ic_fluent_briefcase_off_24_filled',
  'ic_fluent_broad_activity_feed_24_filled',
  'ic_fluent_broom_24_filled',
  'ic_fluent_bug_24_filled',
  'ic_fluent_building_24_filled',
  'ic_fluent_building_bank_24_filled',
  'ic_fluent_building_bank_link_24_filled',
  'ic_fluent_building_bank_toolbox_24_filled',
  'ic_fluent_building_factory_24_filled',
  'ic_fluent_building_government_24_filled',
  'ic_fluent_building_multiple_24_filled',
  'ic_fluent_building_retail_24_filled',
  'ic_fluent_building_retail_money_24_filled',
  'ic_fluent_building_retail_shield_24_filled',
  'ic_fluent_building_retail_toolbox_24_filled',
  'ic_fluent_building_shop_24_filled',
  'ic_fluent_building_skyscraper_24_filled',
  'ic_fluent_calculator_24_filled',
  'ic_fluent_calculator_multiple_24_filled',
  'ic_fluent_calendar_3_day_24_filled',
  'ic_fluent_calendar_add_24_filled',
  'ic_fluent_calendar_agenda_24_filled',
  'ic_fluent_calendar_arrow_down_24_filled',
  'ic_fluent_calendar_assistant_24_filled',
  'ic_fluent_calendar_cancel_24_filled',
  'ic_fluent_calendar_checkmark_24_filled',
  'ic_fluent_calendar_clock_24_filled',
  'ic_fluent_calendar_day_24_filled',
  'ic_fluent_calendar_edit_24_filled',
  'ic_fluent_calendar_empty_24_filled',
  'ic_fluent_calendar_error_24_filled',
  'ic_fluent_calendar_ltr_24_filled',
  'ic_fluent_calendar_month_24_filled',
  'ic_fluent_calendar_multiple_24_filled',
  'ic_fluent_calendar_overdue_24_filled',
  'ic_fluent_calendar_person_24_filled',
  'ic_fluent_calendar_question_mark_24_filled',
  'ic_fluent_calendar_reply_24_filled',
  'ic_fluent_calendar_rtl_24_filled',
  'ic_fluent_calendar_star_24_filled',
  'ic_fluent_calendar_sync_24_filled',
  'ic_fluent_calendar_today_24_filled',
  'ic_fluent_calendar_week_numbers_24_filled',
  'ic_fluent_calendar_week_start_24_filled',
  'ic_fluent_calendar_work_week_24_filled',
  'ic_fluent_call_24_filled',
  'ic_fluent_call_add_24_filled',
  'ic_fluent_call_checkmark_24_filled',
  'ic_fluent_call_dismiss_24_filled',
  'ic_fluent_call_end_24_filled',
  'ic_fluent_call_forward_24_filled',
  'ic_fluent_call_inbound_24_filled',
  'ic_fluent_call_missed_24_filled',
  'ic_fluent_call_outbound_24_filled',
  'ic_fluent_call_park_24_filled',
  'ic_fluent_call_pause_24_filled',
  'ic_fluent_call_prohibited_24_filled',
  'ic_fluent_calligraphy_pen_24_filled',
  'ic_fluent_camera_24_filled',
  'ic_fluent_camera_add_24_filled',
  'ic_fluent_camera_dome_24_filled',
  'ic_fluent_camera_off_24_filled',
  'ic_fluent_camera_switch_24_filled',
  'ic_fluent_caret_24_filled',
  'ic_fluent_caret_down_24_filled',
  'ic_fluent_caret_down_left_24_filled',
  'ic_fluent_caret_left_24_filled',
  'ic_fluent_caret_right_24_filled',
  'ic_fluent_caret_up_24_filled',
  'ic_fluent_cart_24_filled',
  'ic_fluent_cast_24_filled',
  'ic_fluent_cellular_3g_24_filled',
  'ic_fluent_cellular_4g_24_filled',
  'ic_fluent_cellular_5g_24_filled',
  'ic_fluent_cellular_data_1_24_filled',
  'ic_fluent_cellular_data_2_24_filled',
  'ic_fluent_cellular_data_3_24_filled',
  'ic_fluent_cellular_data_4_24_filled',
  'ic_fluent_cellular_data_5_24_filled',
  'ic_fluent_cellular_data_cellular_off_24_filled',
  'ic_fluent_cellular_data_cellular_unavailable_24_filled',
  'ic_fluent_cellular_data_unavailable_24_filled',
  'ic_fluent_cellular_warning_24_filled',
  'ic_fluent_center_horizontal_24_filled',
  'ic_fluent_center_vertical_24_filled',
  'ic_fluent_certificate_24_filled',
  'ic_fluent_channel_24_filled',
  'ic_fluent_channel_add_24_filled',
  'ic_fluent_channel_alert_24_filled',
  'ic_fluent_channel_arrow_left_24_filled',
  'ic_fluent_channel_dismiss_24_filled',
  'ic_fluent_channel_share_24_filled',
  'ic_fluent_channel_subtract_24_filled',
  'ic_fluent_chart_person_24_filled',
  'ic_fluent_chat_24_filled',
  'ic_fluent_chat_bubbles_question_24_filled',
  'ic_fluent_chat_help_24_filled',
  'ic_fluent_chat_multiple_24_filled',
  'ic_fluent_chat_off_24_filled',
  'ic_fluent_chat_settings_24_filled',
  'ic_fluent_chat_video_24_filled',
  'ic_fluent_chat_warning_24_filled',
  'ic_fluent_check_24_filled',
  'ic_fluent_checkbox_1_24_filled',
  'ic_fluent_checkbox_2_24_filled',
  'ic_fluent_checkbox_arrow_right_24_filled',
  'ic_fluent_checkbox_checked_24_filled',
  'ic_fluent_checkbox_indeterminate_24_filled',
  'ic_fluent_checkbox_person_24_filled',
  'ic_fluent_checkbox_unchecked_24_filled',
  'ic_fluent_checkbox_warning_24_filled',
  'ic_fluent_checkmark_24_filled',
  'ic_fluent_checkmark_circle_24_filled',
  'ic_fluent_checkmark_lock_24_filled',
  'ic_fluent_checkmark_square_24_filled',
  'ic_fluent_chevron_circle_down_24_filled',
  'ic_fluent_chevron_circle_right_24_filled',
  'ic_fluent_chevron_down_24_filled',
  'ic_fluent_chevron_left_24_filled',
  'ic_fluent_chevron_right_24_filled',
  'ic_fluent_chevron_up_24_filled',
  'ic_fluent_chevron_up_down_24_filled',
  'ic_fluent_circle_24_filled',
  'ic_fluent_circle_edit_24_filled',
  'ic_fluent_circle_half_fill_24_filled',
  'ic_fluent_circle_line_24_filled',
  'ic_fluent_circle_small_24_filled',
  'ic_fluent_city_24_filled',
  'ic_fluent_class_24_filled',
  'ic_fluent_classification_24_filled',
  'ic_fluent_clear_formatting_24_filled',
  'ic_fluent_clipboard_24_filled',
  'ic_fluent_clipboard_arrow_right_24_filled',
  'ic_fluent_clipboard_checkmark_24_filled',
  'ic_fluent_clipboard_code_24_filled',
  'ic_fluent_clipboard_error_24_filled',
  'ic_fluent_clipboard_heart_24_filled',
  'ic_fluent_clipboard_image_24_filled',
  'ic_fluent_clipboard_letter_24_filled',
  'ic_fluent_clipboard_link_24_filled',
  'ic_fluent_clipboard_more_24_filled',
  'ic_fluent_clipboard_paste_24_filled',
  'ic_fluent_clipboard_pulse_24_filled',
  'ic_fluent_clipboard_search_24_filled',
  'ic_fluent_clipboard_settings_24_filled',
  'ic_fluent_clipboard_task_24_filled',
  'ic_fluent_clipboard_task_add_24_filled',
  'ic_fluent_clipboard_task_list_ltr_24_filled',
  'ic_fluent_clipboard_task_list_rtl_24_filled',
  'ic_fluent_clipboard_text_ltr_24_filled',
  'ic_fluent_clipboard_text_rtl_24_filled',
  'ic_fluent_clock_24_filled',
  'ic_fluent_clock_alarm_24_filled',
  'ic_fluent_clock_arrow_download_24_filled',
  'ic_fluent_clock_dismiss_24_filled',
  'ic_fluent_closed_caption_24_filled',
  'ic_fluent_closed_caption_off_24_filled',
  'ic_fluent_cloud_24_filled',
  'ic_fluent_cloud_arrow_down_24_filled',
  'ic_fluent_cloud_arrow_up_24_filled',
  'ic_fluent_cloud_backup_24_filled',
  'ic_fluent_cloud_checkmark_24_filled',
  'ic_fluent_cloud_dismiss_24_filled',
  'ic_fluent_cloud_download_24_filled',
  'ic_fluent_cloud_flow_24_filled',
  'ic_fluent_cloud_off_24_filled',
  'ic_fluent_cloud_offline_24_filled',
  'ic_fluent_cloud_swap_24_filled',
  'ic_fluent_cloud_sync_24_filled',
  'ic_fluent_cloud_sync_complete_24_filled',
  'ic_fluent_cloud_words_24_filled',
  'ic_fluent_code_24_filled',
  'ic_fluent_collections_24_filled',
  'ic_fluent_collections_add_24_filled',
  'ic_fluent_color_24_filled',
  'ic_fluent_color_background_24_filled',
  'ic_fluent_color_fill_24_filled',
  'ic_fluent_color_line_24_filled',
  'ic_fluent_column_edit_24_filled',
  'ic_fluent_column_triple_24_filled',
  'ic_fluent_column_triple_edit_24_filled',
  'ic_fluent_comma_24_filled',
  'ic_fluent_comment_24_filled',
  'ic_fluent_comment_add_24_filled',
  'ic_fluent_comment_arrow_left_24_filled',
  'ic_fluent_comment_arrow_right_24_filled',
  'ic_fluent_comment_checkmark_24_filled',
  'ic_fluent_comment_dismiss_24_filled',
  'ic_fluent_comment_edit_24_filled',
  'ic_fluent_comment_lightning_24_filled',
  'ic_fluent_comment_mention_24_filled',
  'ic_fluent_comment_multiple_24_filled',
  'ic_fluent_comment_multiple_checkmark_24_filled',
  'ic_fluent_comment_note_24_filled',
  'ic_fluent_comment_off_24_filled',
  'ic_fluent_communication_24_filled',
  'ic_fluent_communication_person_24_filled',
  'ic_fluent_compass_northwest_24_filled',
  'ic_fluent_component_2_double_tap_swipe_down_24_filled',
  'ic_fluent_component_2_double_tap_swipe_up_24_filled',
  'ic_fluent_compose_24_filled',
  'ic_fluent_conference_room_24_filled',
  'ic_fluent_connector_24_filled',
  'ic_fluent_contact_card_24_filled',
  'ic_fluent_contact_card_group_24_filled',
  'ic_fluent_content_settings_24_filled',
  'ic_fluent_contract_down_left_24_filled',
  'ic_fluent_control_button_24_filled',
  'ic_fluent_convert_range_24_filled',
  'ic_fluent_convert_to_table_24_filled',
  'ic_fluent_convert_to_text_24_filled',
  'ic_fluent_convert_to_type_24_filled',
  'ic_fluent_cookies_24_filled',
  'ic_fluent_copy_24_filled',
  'ic_fluent_copy_add_24_filled',
  'ic_fluent_copy_arrow_right_24_filled',
  'ic_fluent_couch_24_filled',
  'ic_fluent_credit_card_person_24_filled',
  'ic_fluent_credit_card_toolbox_24_filled',
  'ic_fluent_crop_24_filled',
  'ic_fluent_crop_interim_24_filled',
  'ic_fluent_crop_interim_off_24_filled',
  'ic_fluent_cube_24_filled',
  'ic_fluent_cube_sync_24_filled',
  'ic_fluent_currency_dollar_euro_24_filled',
  'ic_fluent_currency_dollar_rupee_24_filled',
  'ic_fluent_cursor_24_filled',
  'ic_fluent_cursor_click_24_filled',
  'ic_fluent_cursor_hover_24_filled',
  'ic_fluent_cursor_hover_off_24_filled',
  'ic_fluent_cut_24_filled',
  'ic_fluent_dark_theme_24_filled',
  'ic_fluent_data_area_24_filled',
  'ic_fluent_data_bar_horizontal_24_filled',
  'ic_fluent_data_bar_vertical_24_filled',
  'ic_fluent_data_bar_vertical_add_24_filled',
  'ic_fluent_data_funnel_24_filled',
  'ic_fluent_data_histogram_24_filled',
  'ic_fluent_data_line_24_filled',
  'ic_fluent_data_pie_24_filled',
  'ic_fluent_data_scatter_24_filled',
  'ic_fluent_data_sunburst_24_filled',
  'ic_fluent_data_treemap_24_filled',
  'ic_fluent_data_trending_24_filled',
  'ic_fluent_data_usage_24_filled',
  'ic_fluent_data_usage_edit_24_filled',
  'ic_fluent_data_waterfall_24_filled',
  'ic_fluent_data_whisker_24_filled',
  'ic_fluent_database_24_filled',
  'ic_fluent_database_link_24_filled',
  'ic_fluent_database_search_24_filled',
  'ic_fluent_decimal_arrow_left_24_filled',
  'ic_fluent_decimal_arrow_right_24_filled',
  'ic_fluent_delete_24_filled',
  'ic_fluent_delete_dismiss_24_filled',
  'ic_fluent_delete_off_24_filled',
  'ic_fluent_dentist_24_filled',
  'ic_fluent_design_ideas_24_filled',
  'ic_fluent_desktop_24_filled',
  'ic_fluent_desktop_arrow_right_24_filled',
  'ic_fluent_desktop_keyboard_24_filled',
  'ic_fluent_desktop_pulse_24_filled',
  'ic_fluent_desktop_speaker_24_filled',
  'ic_fluent_desktop_speaker_off_24_filled',
  'ic_fluent_developer_board_24_filled',
  'ic_fluent_device_eq_24_filled',
  'ic_fluent_device_meeting_room_24_filled',
  'ic_fluent_device_meeting_room_remote_24_filled',
  'ic_fluent_diagram_24_filled',
  'ic_fluent_dialpad_24_filled',
  'ic_fluent_dialpad_off_24_filled',
  'ic_fluent_directions_24_filled',
  'ic_fluent_dismiss_24_filled',
  'ic_fluent_dismiss_circle_24_filled',
  'ic_fluent_dismiss_square_24_filled',
  'ic_fluent_diversity_24_filled',
  'ic_fluent_divider_short_24_filled',
  'ic_fluent_divider_tall_24_filled',
  'ic_fluent_dock_24_filled',
  'ic_fluent_dock_panel_left_24_filled',
  'ic_fluent_dock_panel_right_24_filled',
  'ic_fluent_dock_row_24_filled',
  'ic_fluent_doctor_24_filled',
  'ic_fluent_document_24_filled',
  'ic_fluent_document_add_24_filled',
  'ic_fluent_document_arrow_left_24_filled',
  'ic_fluent_document_arrow_right_24_filled',
  'ic_fluent_document_briefcase_24_filled',
  'ic_fluent_document_bullet_list_24_filled',
  'ic_fluent_document_bullet_list_clock_24_filled',
  'ic_fluent_document_bullet_list_off_24_filled',
  'ic_fluent_document_catch_up_24_filled',
  'ic_fluent_document_checkmark_24_filled',
  'ic_fluent_document_chevron_double_24_filled',
  'ic_fluent_document_copy_24_filled',
  'ic_fluent_document_css_24_filled',
  'ic_fluent_document_dismiss_24_filled',
  'ic_fluent_document_edit_24_filled',
  'ic_fluent_document_endnote_24_filled',
  'ic_fluent_document_error_24_filled',
  'ic_fluent_document_footer_24_filled',
  'ic_fluent_document_footer_dismiss_24_filled',
  'ic_fluent_document_footer_remove_24_filled',
  'ic_fluent_document_header_24_filled',
  'ic_fluent_document_header_dismiss_24_filled',
  'ic_fluent_document_header_footer_24_filled',
  'ic_fluent_document_header_remove_24_filled',
  'ic_fluent_document_heart_24_filled',
  'ic_fluent_document_heart_pulse_24_filled',
  'ic_fluent_document_javascript_24_filled',
  'ic_fluent_document_landscape_24_filled',
  'ic_fluent_document_landscape_data_24_filled',
  'ic_fluent_document_link_24_filled',
  'ic_fluent_document_margins_24_filled',
  'ic_fluent_document_multiple_24_filled',
  'ic_fluent_document_multiple_percent_24_filled',
  'ic_fluent_document_multiple_prohibited_24_filled',
  'ic_fluent_document_one_page_24_filled',
  'ic_fluent_document_page_bottom_center_24_filled',
  'ic_fluent_document_page_bottom_left_24_filled',
  'ic_fluent_document_page_bottom_right_24_filled',
  'ic_fluent_document_page_break_24_filled',
  'ic_fluent_document_page_number_24_filled',
  'ic_fluent_document_page_top_center_24_filled',
  'ic_fluent_document_page_top_left_24_filled',
  'ic_fluent_document_page_top_right_24_filled',
  'ic_fluent_document_pdf_24_filled',
  'ic_fluent_document_percent_24_filled',
  'ic_fluent_document_pill_24_filled',
  'ic_fluent_document_prohibited_24_filled',
  'ic_fluent_document_question_mark_24_filled',
  'ic_fluent_document_ribbon_24_filled',
  'ic_fluent_document_save_24_filled',
  'ic_fluent_document_search_24_filled',
  'ic_fluent_document_split_hint_24_filled',
  'ic_fluent_document_split_hint_off_24_filled',
  'ic_fluent_document_sync_24_filled',
  'ic_fluent_document_table_24_filled',
  'ic_fluent_document_text_24_filled',
  'ic_fluent_document_text_link_24_filled',
  'ic_fluent_document_toolbox_24_filled',
  'ic_fluent_document_width_24_filled',
  'ic_fluent_door_arrow_left_24_filled',
  'ic_fluent_door_tag_24_filled',
  'ic_fluent_double_swipe_down_24_filled',
  'ic_fluent_double_swipe_up_24_filled',
  'ic_fluent_drafts_24_filled',
  'ic_fluent_drag_24_filled',
  'ic_fluent_draw_shape_24_filled',
  'ic_fluent_draw_text_24_filled',
  'ic_fluent_drink_beer_24_filled',
  'ic_fluent_drink_coffee_24_filled',
  'ic_fluent_drink_margarita_24_filled',
  'ic_fluent_drink_to_go_24_filled',
  'ic_fluent_drink_wine_24_filled',
  'ic_fluent_drive_train_24_filled',
  'ic_fluent_drop_24_filled',
  'ic_fluent_dual_screen_24_filled',
  'ic_fluent_dual_screen_add_24_filled',
  'ic_fluent_dual_screen_arrow_right_24_filled',
  'ic_fluent_dual_screen_arrow_up_24_filled',
  'ic_fluent_dual_screen_clock_24_filled',
  'ic_fluent_dual_screen_closed_alert_24_filled',
  'ic_fluent_dual_screen_desktop_24_filled',
  'ic_fluent_dual_screen_dismiss_24_filled',
  'ic_fluent_dual_screen_group_24_filled',
  'ic_fluent_dual_screen_header_24_filled',
  'ic_fluent_dual_screen_lock_24_filled',
  'ic_fluent_dual_screen_mirror_24_filled',
  'ic_fluent_dual_screen_pagination_24_filled',
  'ic_fluent_dual_screen_settings_24_filled',
  'ic_fluent_dual_screen_span_24_filled',
  'ic_fluent_dual_screen_speaker_24_filled',
  'ic_fluent_dual_screen_status_bar_24_filled',
  'ic_fluent_dual_screen_tablet_24_filled',
  'ic_fluent_dual_screen_update_24_filled',
  'ic_fluent_dual_screen_vertical_scroll_24_filled',
  'ic_fluent_dual_screen_vibrate_24_filled',
  'ic_fluent_dumbbell_24_filled',
  'ic_fluent_earth_24_filled',
  'ic_fluent_edit_24_filled',
  'ic_fluent_edit_off_24_filled',
  'ic_fluent_edit_settings_24_filled',
  'ic_fluent_emoji_24_filled',
  'ic_fluent_emoji_add_24_filled',
  'ic_fluent_emoji_angry_24_filled',
  'ic_fluent_emoji_hand_24_filled',
  'ic_fluent_emoji_laugh_24_filled',
  'ic_fluent_emoji_meh_24_filled',
  'ic_fluent_emoji_multiple_24_filled',
  'ic_fluent_emoji_sad_24_filled',
  'ic_fluent_emoji_surprise_24_filled',
  'ic_fluent_engine_24_filled',
  'ic_fluent_equal_off_24_filled',
  'ic_fluent_eraser_24_filled',
  'ic_fluent_eraser_medium_24_filled',
  'ic_fluent_eraser_segment_24_filled',
  'ic_fluent_eraser_small_24_filled',
  'ic_fluent_eraser_tool_24_filled',
  'ic_fluent_error_circle_24_filled',
  'ic_fluent_expand_up_left_24_filled',
  'ic_fluent_expand_up_right_24_filled',
  'ic_fluent_extended_dock_24_filled',
  'ic_fluent_extension_24_filled',
  'ic_fluent_eye_hide_24_filled',
  'ic_fluent_eye_show_24_filled',
  'ic_fluent_eye_tracking_off_24_filled',
  'ic_fluent_eye_tracking_on_24_filled',
  'ic_fluent_eyedropper_24_filled',
  'ic_fluent_f_stop_24_filled',
  'ic_fluent_fast_acceleration_24_filled',
  'ic_fluent_fast_forward_24_filled',
  'ic_fluent_filter_24_filled',
  'ic_fluent_filter_dismiss_24_filled',
  'ic_fluent_filter_sync_24_filled',
  'ic_fluent_fingerprint_24_filled',
  'ic_fluent_fixed_width_24_filled',
  'ic_fluent_flag_24_filled',
  'ic_fluent_flag_off_24_filled',
  'ic_fluent_flag_pride_24_filled',
  'ic_fluent_flash_auto_24_filled',
  'ic_fluent_flash_checkmark_24_filled',
  'ic_fluent_flash_off_24_filled',
  'ic_fluent_flash_on_24_filled',
  'ic_fluent_flashlight_24_filled',
  'ic_fluent_flashlight_off_24_filled',
  'ic_fluent_flip_horizontal_24_filled',
  'ic_fluent_flip_vertical_24_filled',
  'ic_fluent_fluid_24_filled',
  'ic_fluent_folder_24_filled',
  'ic_fluent_folder_add_24_filled',
  'ic_fluent_folder_arrow_right_24_filled',
  'ic_fluent_folder_arrow_up_24_filled',
  'ic_fluent_folder_link_24_filled',
  'ic_fluent_folder_open_24_filled',
  'ic_fluent_folder_prohibited_24_filled',
  'ic_fluent_folder_swap_24_filled',
  'ic_fluent_folder_zip_24_filled',
  'ic_fluent_font_decrease_24_filled',
  'ic_fluent_font_increase_24_filled',
  'ic_fluent_font_space_tracking_in_24_filled',
  'ic_fluent_font_space_tracking_out_24_filled',
  'ic_fluent_food_24_filled',
  'ic_fluent_food_cake_24_filled',
  'ic_fluent_food_egg_24_filled',
  'ic_fluent_food_pizza_24_filled',
  'ic_fluent_food_toast_24_filled',
  'ic_fluent_form_new_24_filled',
  'ic_fluent_fps_120_24_filled',
  'ic_fluent_fps_240_20_filled',
  'ic_fluent_fps_240_24_filled',
  'ic_fluent_fps_30_24_filled',
  'ic_fluent_fps_60_24_filled',
  'ic_fluent_fps_960_24_filled',
  'ic_fluent_full_screen_maximize_24_filled',
  'ic_fluent_full_screen_minimize_24_filled',
  'ic_fluent_games_24_filled',
  'ic_fluent_gantt_chart_24_filled',
  'ic_fluent_gas_24_filled',
  'ic_fluent_gas_pump_24_filled',
  'ic_fluent_gauge_24_filled',
  'ic_fluent_gavel_24_filled',
  'ic_fluent_gesture_24_filled',
  'ic_fluent_gif_24_filled',
  'ic_fluent_gift_24_filled',
  'ic_fluent_gift_card_add_24_filled',
  'ic_fluent_glance_24_filled',
  'ic_fluent_glasses_24_filled',
  'ic_fluent_glasses_off_24_filled',
  'ic_fluent_globe_24_filled',
  'ic_fluent_globe_add_24_filled',
  'ic_fluent_globe_clock_24_filled',
  'ic_fluent_globe_desktop_24_filled',
  'ic_fluent_globe_location_24_filled',
  'ic_fluent_globe_person_24_filled',
  'ic_fluent_globe_search_24_filled',
  'ic_fluent_globe_shield_24_filled',
  'ic_fluent_globe_surface_24_filled',
  'ic_fluent_globe_video_24_filled',
  'ic_fluent_grid_24_filled',
  'ic_fluent_grid_dots_24_filled',
  'ic_fluent_group_24_filled',
  'ic_fluent_group_dismiss_24_filled',
  'ic_fluent_group_list_24_filled',
  'ic_fluent_group_return_24_filled',
  'ic_fluent_guardian_24_filled',
  'ic_fluent_guest_24_filled',
  'ic_fluent_guest_add_24_filled',
  'ic_fluent_guitar_24_filled',
  'ic_fluent_hand_draw_24_filled',
  'ic_fluent_hand_left_24_filled',
  'ic_fluent_hand_right_24_filled',
  'ic_fluent_handshake_24_filled',
  'ic_fluent_hat_graduation_24_filled',
  'ic_fluent_hd_24_filled',
  'ic_fluent_hdr_24_filled',
  'ic_fluent_headphones_24_filled',
  'ic_fluent_headphones_sound_wave_24_filled',
  'ic_fluent_headset_24_filled',
  'ic_fluent_headset_add_24_filled',
  'ic_fluent_headset_vr_24_filled',
  'ic_fluent_heart_24_filled',
  'ic_fluent_heart_pulse_24_filled',
  'ic_fluent_highlight_24_filled',
  'ic_fluent_highlight_accent_24_filled',
  'ic_fluent_history_24_filled',
  'ic_fluent_home_24_filled',
  'ic_fluent_home_add_24_filled',
  'ic_fluent_home_checkmark_24_filled',
  'ic_fluent_home_person_24_filled',
  'ic_fluent_icons_24_filled',
  'ic_fluent_image_24_filled',
  'ic_fluent_image_add_24_filled',
  'ic_fluent_image_alt_text_24_filled',
  'ic_fluent_image_arrow_back_24_filled',
  'ic_fluent_image_arrow_counterclockwise_24_filled',
  'ic_fluent_image_arrow_forward_24_filled',
  'ic_fluent_image_copy_24_filled',
  'ic_fluent_image_edit_24_filled',
  'ic_fluent_image_globe_24_filled',
  'ic_fluent_image_multiple_24_filled',
  'ic_fluent_image_off_24_filled',
  'ic_fluent_image_prohibited_24_filled',
  'ic_fluent_image_reflection_24_filled',
  'ic_fluent_image_search_24_filled',
  'ic_fluent_image_shadow_24_filled',
  'ic_fluent_immersive_reader_24_filled',
  'ic_fluent_important_24_filled',
  'ic_fluent_incognito_24_filled',
  'ic_fluent_info_24_filled',
  'ic_fluent_ink_stroke_24_filled',
  'ic_fluent_inking_tool_24_filled',
  'ic_fluent_inking_tool_accent_24_filled',
  'ic_fluent_inprivate_account_24_filled',
  'ic_fluent_ios_arrow_left_24_filled',
  'ic_fluent_ios_arrow_ltr_24_filled',
  'ic_fluent_ios_arrow_right_24_filled',
  'ic_fluent_ios_arrow_rtl_24_filled',
  'ic_fluent_iot_24_filled',
  'ic_fluent_javascript_24_filled',
  'ic_fluent_key_24_filled',
  'ic_fluent_keyboard_123_24_filled',
  'ic_fluent_keyboard_24_filled',
  'ic_fluent_keyboard_dock_24_filled',
  'ic_fluent_keyboard_layout_float_24_filled',
  'ic_fluent_keyboard_layout_one_handed_left_24_filled',
  'ic_fluent_keyboard_layout_resize_24_filled',
  'ic_fluent_keyboard_layout_split_24_filled',
  'ic_fluent_keyboard_shift_24_filled',
  'ic_fluent_keyboard_shift_uppercase_24_filled',
  'ic_fluent_keyboard_tab_24_filled',
  'ic_fluent_laptop_24_filled',
  'ic_fluent_lasso_24_filled',
  'ic_fluent_launcher_settings_24_filled',
  'ic_fluent_layer_24_filled',
  'ic_fluent_leaf_one_24_filled',
  'ic_fluent_leaf_three_24_filled',
  'ic_fluent_leaf_two_24_filled',
  'ic_fluent_learning_app_24_filled',
  'ic_fluent_library_24_filled',
  'ic_fluent_lightbulb_24_filled',
  'ic_fluent_lightbulb_circle_24_filled',
  'ic_fluent_lightbulb_filament_24_filled',
  'ic_fluent_likert_24_filled',
  'ic_fluent_line_style_24_filled',
  'ic_fluent_link_24_filled',
  'ic_fluent_link_dismiss_24_filled',
  'ic_fluent_link_edit_24_filled',
  'ic_fluent_link_square_24_filled',
  'ic_fluent_list_24_filled',
  'ic_fluent_live_24_filled',
  'ic_fluent_live_off_24_filled',
  'ic_fluent_local_language_24_filled',
  'ic_fluent_local_language_zi_24_filled',
  'ic_fluent_location_24_filled',
  'ic_fluent_location_dismiss_24_filled',
  'ic_fluent_location_live_24_filled',
  'ic_fluent_location_off_24_filled',
  'ic_fluent_lock_closed_24_filled',
  'ic_fluent_lock_multiple_24_filled',
  'ic_fluent_lock_open_24_filled',
  'ic_fluent_lock_shield_24_filled',
  'ic_fluent_lottery_24_filled',
  'ic_fluent_luggage_24_filled',
  'ic_fluent_mail_24_filled',
  'ic_fluent_mail_add_24_filled',
  'ic_fluent_mail_alert_24_filled',
  'ic_fluent_mail_all_24_filled',
  'ic_fluent_mail_arrow_up_24_filled',
  'ic_fluent_mail_clock_24_filled',
  'ic_fluent_mail_copy_24_filled',
  'ic_fluent_mail_dismiss_24_filled',
  'ic_fluent_mail_error_24_filled',
  'ic_fluent_mail_inbox_24_filled',
  'ic_fluent_mail_inbox_add_24_filled',
  'ic_fluent_mail_inbox_all_24_filled',
  'ic_fluent_mail_inbox_arrow_right_24_filled',
  'ic_fluent_mail_inbox_arrow_up_24_filled',
  'ic_fluent_mail_inbox_checkmark_24_filled',
  'ic_fluent_mail_inbox_dismiss_24_filled',
  'ic_fluent_mail_link_24_filled',
  'ic_fluent_mail_multiple_24_filled',
  'ic_fluent_mail_off_24_filled',
  'ic_fluent_mail_prohibited_24_filled',
  'ic_fluent_mail_read_24_filled',
  'ic_fluent_mail_template_24_filled',
  'ic_fluent_mail_unread_24_filled',
  'ic_fluent_map_24_filled',
  'ic_fluent_map_drive_24_filled',
  'ic_fluent_match_app_layout_24_filled',
  'ic_fluent_math_format_linear_24_filled',
  'ic_fluent_math_format_professional_24_filled',
  'ic_fluent_math_formula_24_filled',
  'ic_fluent_maximize_24_filled',
  'ic_fluent_meet_now_24_filled',
  'ic_fluent_megaphone_24_filled',
  'ic_fluent_megaphone_off_24_filled',
  'ic_fluent_mention_24_filled',
  'ic_fluent_merge_24_filled',
  'ic_fluent_mic_off_24_filled',
  'ic_fluent_mic_on_24_filled',
  'ic_fluent_mic_prohibited_24_filled',
  'ic_fluent_mic_settings_24_filled',
  'ic_fluent_mic_sparkle_24_filled',
  'ic_fluent_microscope_24_filled',
  'ic_fluent_midi_24_filled',
  'ic_fluent_mobile_optimized_24_filled',
  'ic_fluent_molecule_24_filled',
  'ic_fluent_money_24_filled',
  'ic_fluent_money_calculator_24_filled',
  'ic_fluent_more_horizontal_24_filled',
  'ic_fluent_more_vertical_24_filled',
  'ic_fluent_movies_and_tv_24_filled',
  'ic_fluent_multiplier_1_2x_24_filled',
  'ic_fluent_multiplier_1_5x_24_filled',
  'ic_fluent_multiplier_1_8x_24_filled',
  'ic_fluent_multiplier_1x_24_filled',
  'ic_fluent_multiplier_2x_24_filled',
  'ic_fluent_multiplier_5x_24_filled',
  'ic_fluent_multiselect_24_filled',
  'ic_fluent_music_note_1_24_filled',
  'ic_fluent_music_note_2_24_filled',
  'ic_fluent_my_location_24_filled',
  'ic_fluent_navigation_24_filled',
  'ic_fluent_navigation_unread_24_filled',
  'ic_fluent_network_check_24_filled',
  'ic_fluent_new_24_filled',
  'ic_fluent_news_24_filled',
  'ic_fluent_next_24_filled',
  'ic_fluent_note_24_filled',
  'ic_fluent_note_add_24_filled',
  'ic_fluent_note_edit_24_filled',
  'ic_fluent_notebook_24_filled',
  'ic_fluent_notebook_add_24_filled',
  'ic_fluent_notebook_error_24_filled',
  'ic_fluent_notebook_lightning_24_filled',
  'ic_fluent_notebook_question_mark_24_filled',
  'ic_fluent_notebook_section_24_filled',
  'ic_fluent_notebook_section_arrow_right_24_filled',
  'ic_fluent_notebook_subsection_24_filled',
  'ic_fluent_notebook_sync_24_filled',
  'ic_fluent_notepad_24_filled',
  'ic_fluent_notepad_person_24_filled',
  'ic_fluent_number_row_24_filled',
  'ic_fluent_number_symbol_24_filled',
  'ic_fluent_number_symbol_dismiss_24_filled',
  'ic_fluent_number_symbol_square_24_filled',
  'ic_fluent_office_apps_24_filled',
  'ic_fluent_open_24_filled',
  'ic_fluent_open_folder_24_filled',
  'ic_fluent_open_off_24_filled',
  'ic_fluent_options_24_filled',
  'ic_fluent_organization_24_filled',
  'ic_fluent_orientation_24_filled',
  'ic_fluent_padding_down_24_filled',
  'ic_fluent_padding_left_24_filled',
  'ic_fluent_padding_right_24_filled',
  'ic_fluent_padding_top_24_filled',
  'ic_fluent_page_fit_24_filled',
  'ic_fluent_paint_brush_24_filled',
  'ic_fluent_paint_brush_arrow_down_24_filled',
  'ic_fluent_paint_brush_arrow_up_24_filled',
  'ic_fluent_paint_bucket_24_filled',
  'ic_fluent_pair_24_filled',
  'ic_fluent_pane_close_24_filled',
  'ic_fluent_pane_open_24_filled',
  'ic_fluent_panel_left_24_filled',
  'ic_fluent_panel_right_24_filled',
  'ic_fluent_panel_right_contract_24_filled',
  'ic_fluent_panel_right_expand_24_filled',
  'ic_fluent_password_24_filled',
  'ic_fluent_patch_24_filled',
  'ic_fluent_patient_24_filled',
  'ic_fluent_pause_24_filled',
  'ic_fluent_pause_circle_24_filled',
  'ic_fluent_payment_24_filled',
  'ic_fluent_people_24_filled',
  'ic_fluent_people_add_24_filled',
  'ic_fluent_people_audience_24_filled',
  'ic_fluent_people_checkmark_24_filled',
  'ic_fluent_people_community_24_filled',
  'ic_fluent_people_community_add_24_filled',
  'ic_fluent_people_error_24_filled',
  'ic_fluent_people_money_24_filled',
  'ic_fluent_people_search_24_filled',
  'ic_fluent_people_settings_24_filled',
  'ic_fluent_people_swap_24_filled',
  'ic_fluent_people_team_24_filled',
  'ic_fluent_people_team_add_24_filled',
  'ic_fluent_people_team_delete_24_filled',
  'ic_fluent_people_team_toolbox_24_filled',
  'ic_fluent_person_24_filled',
  'ic_fluent_person_accounts_24_filled',
  'ic_fluent_person_add_24_filled',
  'ic_fluent_person_arrow_left_24_filled',
  'ic_fluent_person_arrow_right_24_filled',
  'ic_fluent_person_available_24_filled',
  'ic_fluent_person_board_24_filled',
  'ic_fluent_person_call_24_filled',
  'ic_fluent_person_chat_24_filled',
  'ic_fluent_person_clock_24_filled',
  'ic_fluent_person_delete_24_filled',
  'ic_fluent_person_feedback_24_filled',
  'ic_fluent_person_lock_24_filled',
  'ic_fluent_person_mail_24_filled',
  'ic_fluent_person_money_24_filled',
  'ic_fluent_person_note_24_filled',
  'ic_fluent_person_pill_24_filled',
  'ic_fluent_person_prohibited_24_filled',
  'ic_fluent_person_question_mark_24_filled',
  'ic_fluent_person_support_24_filled',
  'ic_fluent_person_swap_24_filled',
  'ic_fluent_person_voice_24_filled',
  'ic_fluent_phone_24_filled',
  'ic_fluent_phone_add_24_filled',
  'ic_fluent_phone_arrow_right_24_filled',
  'ic_fluent_phone_desktop_24_filled',
  'ic_fluent_phone_dismiss_24_filled',
  'ic_fluent_phone_laptop_24_filled',
  'ic_fluent_phone_link_setup_24_filled',
  'ic_fluent_phone_lock_24_filled',
  'ic_fluent_phone_page_header_24_filled',
  'ic_fluent_phone_pagination_24_filled',
  'ic_fluent_phone_screen_time_24_filled',
  'ic_fluent_phone_shake_24_filled',
  'ic_fluent_phone_span_in_24_filled',
  'ic_fluent_phone_span_out_24_filled',
  'ic_fluent_phone_speaker_24_filled',
  'ic_fluent_phone_status_bar_24_filled',
  'ic_fluent_phone_tablet_24_filled',
  'ic_fluent_phone_update_24_filled',
  'ic_fluent_phone_vertical_scroll_24_filled',
  'ic_fluent_phone_vibrate_24_filled',
  'ic_fluent_photo_filter_24_filled',
  'ic_fluent_pi_24_filled',
  'ic_fluent_picture_in_picture_24_filled',
  'ic_fluent_pill_24_filled',
  'ic_fluent_pin_24_filled',
  'ic_fluent_pin_off_24_filled',
  'ic_fluent_pivot_24_filled',
  'ic_fluent_play_24_filled',
  'ic_fluent_play_circle_24_filled',
  'ic_fluent_plug_disconnected_24_filled',
  'ic_fluent_point_scan_24_filled',
  'ic_fluent_poll_24_filled',
  'ic_fluent_port_hdmi_24_filled',
  'ic_fluent_port_micro_usb_24_filled',
  'ic_fluent_port_usb_a_24_filled',
  'ic_fluent_port_usb_c_24_filled',
  'ic_fluent_position_backward_24_filled',
  'ic_fluent_position_forward_24_filled',
  'ic_fluent_position_to_back_24_filled',
  'ic_fluent_position_to_front_24_filled',
  'ic_fluent_power_24_filled',
  'ic_fluent_predictions_24_filled',
  'ic_fluent_premium_24_filled',
  'ic_fluent_premium_person_24_filled',
  'ic_fluent_presenter_24_filled',
  'ic_fluent_presenter_off_24_filled',
  'ic_fluent_preview_link_24_filled',
  'ic_fluent_previous_24_filled',
  'ic_fluent_print_24_filled',
  'ic_fluent_print_add_24_filled',
  'ic_fluent_production_24_filled',
  'ic_fluent_production_checkmark_24_filled',
  'ic_fluent_prohibited_24_filled',
  'ic_fluent_prohibited_multiple_24_filled',
  'ic_fluent_projection_screen_24_filled',
  'ic_fluent_projection_screen_dismiss_24_filled',
  'ic_fluent_protocol_handler_24_filled',
  'ic_fluent_pulse_24_filled',
  'ic_fluent_pulse_square_24_filled',
  'ic_fluent_puzzle_cube_24_filled',
  'ic_fluent_puzzle_piece_24_filled',
  'ic_fluent_qr_code_24_filled',
  'ic_fluent_question_24_filled',
  'ic_fluent_question_circle_24_filled',
  'ic_fluent_quiz_new_24_filled',
  'ic_fluent_radio_button_24_filled',
  'ic_fluent_rating_mature_24_filled',
  'ic_fluent_ratio_one_to_one_24_filled',
  'ic_fluent_re_order_24_filled',
  'ic_fluent_re_order_dots_horizontal_24_filled',
  'ic_fluent_re_order_dots_vertical_24_filled',
  'ic_fluent_read_aloud_24_filled',
  'ic_fluent_reading_list_24_filled',
  'ic_fluent_reading_list_add_24_filled',
  'ic_fluent_reading_mode_mobile_24_filled',
  'ic_fluent_real_estate_24_filled',
  'ic_fluent_receipt_24_filled',
  'ic_fluent_receipt_add_24_filled',
  'ic_fluent_receipt_bag_24_filled',
  'ic_fluent_receipt_cube_24_filled',
  'ic_fluent_receipt_money_24_filled',
  'ic_fluent_receipt_play_24_filled',
  'ic_fluent_record_24_filled',
  'ic_fluent_record_stop_24_filled',
  'ic_fluent_rectangle_landscape_24_filled',
  'ic_fluent_rename_24_filled',
  'ic_fluent_resize_image_24_filled',
  'ic_fluent_resize_large_24_filled',
  'ic_fluent_resize_small_24_filled',
  'ic_fluent_resize_table_24_filled',
  'ic_fluent_resize_video_24_filled',
  'ic_fluent_reward_24_filled',
  'ic_fluent_rewind_24_filled',
  'ic_fluent_ribbon_24_filled',
  'ic_fluent_ribbon_add_24_filled',
  'ic_fluent_ribbon_star_24_filled',
  'ic_fluent_road_cone_24_filled',
  'ic_fluent_rocket_24_filled',
  'ic_fluent_rotate_left_24_filled',
  'ic_fluent_rotate_right_24_filled',
  'ic_fluent_router_24_filled',
  'ic_fluent_row_triple_24_filled',
  'ic_fluent_rss_24_filled',
  'ic_fluent_ruler_24_filled',
  'ic_fluent_run_24_filled',
  'ic_fluent_save_24_filled',
  'ic_fluent_save_arrow_right_24_filled',
  'ic_fluent_save_copy_24_filled',
  'ic_fluent_save_edit_24_filled',
  'ic_fluent_savings_24_filled',
  'ic_fluent_scale_fill_24_filled',
  'ic_fluent_scale_fit_24_filled',
  'ic_fluent_scales_24_filled',
  'ic_fluent_scan_24_filled',
  'ic_fluent_scan_object_24_filled',
  'ic_fluent_scan_table_24_filled',
  'ic_fluent_scan_text_24_filled',
  'ic_fluent_scan_thumb_up_24_filled',
  'ic_fluent_scan_thumb_up_off_24_filled',
  'ic_fluent_scan_type_24_filled',
  'ic_fluent_scratchpad_24_filled',
  'ic_fluent_screenshot_24_filled',
  'ic_fluent_search_24_filled',
  'ic_fluent_search_info_24_filled',
  'ic_fluent_search_square_24_filled',
  'ic_fluent_search_visual_24_filled',
  'ic_fluent_select_all_off_24_filled',
  'ic_fluent_select_all_on_24_filled',
  'ic_fluent_select_object_24_filled',
  'ic_fluent_send_24_filled',
  'ic_fluent_send_clock_24_filled',
  'ic_fluent_send_copy_24_filled',
  'ic_fluent_serial_port_24_filled',
  'ic_fluent_server_24_filled',
  'ic_fluent_service_bell_24_filled',
  'ic_fluent_set_top_stack_24_filled',
  'ic_fluent_settings_24_filled',
  'ic_fluent_shape_exclude_24_filled',
  'ic_fluent_shape_intersect_24_filled',
  'ic_fluent_shape_subtract_24_filled',
  'ic_fluent_shape_union_24_filled',
  'ic_fluent_shapes_24_filled',
  'ic_fluent_share_24_filled',
  'ic_fluent_share_android_24_filled',
  'ic_fluent_share_close_tray_24_filled',
  'ic_fluent_share_ios_24_filled',
  'ic_fluent_share_screen_person_24_filled',
  'ic_fluent_share_screen_person_overlay_24_filled',
  'ic_fluent_share_screen_person_overlay_inside_24_filled',
  'ic_fluent_share_screen_start_24_filled',
  'ic_fluent_share_screen_stop_24_filled',
  'ic_fluent_shield_24_filled',
  'ic_fluent_shield_badge_24_filled',
  'ic_fluent_shield_checkmark_24_filled',
  'ic_fluent_shield_dismiss_24_filled',
  'ic_fluent_shield_error_24_filled',
  'ic_fluent_shield_keyhole_24_filled',
  'ic_fluent_shield_prohibited_24_filled',
  'ic_fluent_shield_task_24_filled',
  'ic_fluent_shield_video_24_filled',
  'ic_fluent_shifts_24_filled',
  'ic_fluent_shifts_30_minutes_24_filled',
  'ic_fluent_shifts_activity_24_filled',
  'ic_fluent_shifts_add_24_filled',
  'ic_fluent_shifts_availability_24_filled',
  'ic_fluent_shifts_checkmark_24_filled',
  'ic_fluent_shifts_day_24_filled',
  'ic_fluent_shifts_open_24_filled',
  'ic_fluent_shifts_prohibited_24_filled',
  'ic_fluent_shifts_question_mark_24_filled',
  'ic_fluent_shifts_team_24_filled',
  'ic_fluent_shopping_bag_24_filled',
  'ic_fluent_shortpick_24_filled',
  'ic_fluent_sign_out_24_filled',
  'ic_fluent_signature_24_filled',
  'ic_fluent_signed_24_filled',
  'ic_fluent_sim_24_filled',
  'ic_fluent_skip_backward_10_24_filled',
  'ic_fluent_skip_forward_10_24_filled',
  'ic_fluent_skip_forward_30_24_filled',
  'ic_fluent_skip_forward_tab_24_filled',
  'ic_fluent_sleep_24_filled',
  'ic_fluent_slide_add_24_filled',
  'ic_fluent_slide_design_24_filled',
  'ic_fluent_slide_eraser_24_filled',
  'ic_fluent_slide_grid_24_filled',
  'ic_fluent_slide_hide_24_filled',
  'ic_fluent_slide_layout_24_filled',
  'ic_fluent_slide_microphone_24_filled',
  'ic_fluent_slide_multiple_24_filled',
  'ic_fluent_slide_multiple_arrow_right_24_filled',
  'ic_fluent_slide_multiple_search_24_filled',
  'ic_fluent_slide_search_24_filled',
  'ic_fluent_slide_settings_24_filled',
  'ic_fluent_slide_size_24_filled',
  'ic_fluent_slide_text_24_filled',
  'ic_fluent_slide_transition_24_filled',
  'ic_fluent_smartwatch_24_filled',
  'ic_fluent_smartwatch_dot_24_filled',
  'ic_fluent_snooze_24_filled',
  'ic_fluent_sound_source_24_filled',
  'ic_fluent_spacebar_24_filled',
  'ic_fluent_sparkle_24_filled',
  'ic_fluent_speaker_0_24_filled',
  'ic_fluent_speaker_1_24_filled',
  'ic_fluent_speaker_2_24_filled',
  'ic_fluent_speaker_bluetooth_24_filled',
  'ic_fluent_speaker_edit_24_filled',
  'ic_fluent_speaker_mute_24_filled',
  'ic_fluent_speaker_off_24_filled',
  'ic_fluent_speaker_settings_24_filled',
  'ic_fluent_speaker_usb_24_filled',
  'ic_fluent_split_horizontal_24_filled',
  'ic_fluent_split_vertical_24_filled',
  'ic_fluent_sport_24_filled',
  'ic_fluent_sport_american_football_24_filled',
  'ic_fluent_sport_baseball_24_filled',
  'ic_fluent_sport_basketball_24_filled',
  'ic_fluent_sport_hockey_24_filled',
  'ic_fluent_sport_soccer_24_filled',
  'ic_fluent_square_arrow_forward_24_filled',
  'ic_fluent_square_multiple_24_filled',
  'ic_fluent_stack_24_filled',
  'ic_fluent_stack_star_24_filled',
  'ic_fluent_star_24_filled',
  'ic_fluent_star_add_24_filled',
  'ic_fluent_star_arrow_right_end_24_filled',
  'ic_fluent_star_arrow_right_start_24_filled',
  'ic_fluent_star_edit_24_filled',
  'ic_fluent_star_emphasis_24_filled',
  'ic_fluent_star_half_24_filled',
  'ic_fluent_star_line_horizontal_3_24_filled',
  'ic_fluent_star_off_24_filled',
  'ic_fluent_star_one_quarter_24_filled',
  'ic_fluent_star_prohibited_24_filled',
  'ic_fluent_star_settings_24_filled',
  'ic_fluent_star_three_quarter_24_filled',
  'ic_fluent_status_24_filled',
  'ic_fluent_steps_24_filled',
  'ic_fluent_stethoscope_24_filled',
  'ic_fluent_sticker_24_filled',
  'ic_fluent_sticker_add_24_filled',
  'ic_fluent_stop_24_filled',
  'ic_fluent_storage_24_filled',
  'ic_fluent_store_microsoft_24_filled',
  'ic_fluent_stream_24_filled',
  'ic_fluent_strikethrough_ga_na_24_filled',
  'ic_fluent_style_guide_24_filled',
  'ic_fluent_sub_grid_24_filled',
  'ic_fluent_subtract_24_filled',
  'ic_fluent_subtract_circle_24_filled',
  'ic_fluent_subtract_square_24_filled',
  'ic_fluent_surface_earbuds_24_filled',
  'ic_fluent_surface_hub_24_filled',
  'ic_fluent_swipe_down_24_filled',
  'ic_fluent_swipe_right_24_filled',
  'ic_fluent_swipe_up_24_filled',
  'ic_fluent_symbols_24_filled',
  'ic_fluent_syringe_24_filled',
  'ic_fluent_system_24_filled',
  'ic_fluent_tab_24_filled',
  'ic_fluent_tab_add_24_filled',
  'ic_fluent_tab_arrow_left_24_filled',
  'ic_fluent_tab_desktop_arrow_clockwise_24_filled',
  'ic_fluent_tab_desktop_bottom_24_filled',
  'ic_fluent_tab_desktop_image_24_filled',
  'ic_fluent_tab_desktop_multiple_bottom_24_filled',
  'ic_fluent_tab_in_private_24_filled',
  'ic_fluent_tab_inprivate_account_24_filled',
  'ic_fluent_tab_prohibited_24_filled',
  'ic_fluent_tab_shield_dismiss_24_filled',
  'ic_fluent_table_24_filled',
  'ic_fluent_table_add_24_filled',
  'ic_fluent_table_cell_edit_24_filled',
  'ic_fluent_table_cells_merge_24_filled',
  'ic_fluent_table_cells_split_24_filled',
  'ic_fluent_table_delete_column_24_filled',
  'ic_fluent_table_delete_row_24_filled',
  'ic_fluent_table_dismiss_24_filled',
  'ic_fluent_table_edit_24_filled',
  'ic_fluent_table_freeze_column_24_filled',
  'ic_fluent_table_freeze_column_and_row_24_filled',
  'ic_fluent_table_freeze_row_24_filled',
  'ic_fluent_table_insert_column_24_filled',
  'ic_fluent_table_insert_row_24_filled',
  'ic_fluent_table_move_above_24_filled',
  'ic_fluent_table_move_below_24_filled',
  'ic_fluent_table_move_left_24_filled',
  'ic_fluent_table_move_right_24_filled',
  'ic_fluent_table_resize_column_24_filled',
  'ic_fluent_table_resize_row_24_filled',
  'ic_fluent_table_settings_24_filled',
  'ic_fluent_table_simple_24_filled',
  'ic_fluent_table_stack_above_24_filled',
  'ic_fluent_table_stack_below_24_filled',
  'ic_fluent_table_stack_left_24_filled',
  'ic_fluent_table_stack_right_24_filled',
  'ic_fluent_table_switch_24_filled',
  'ic_fluent_tablet_24_filled',
  'ic_fluent_tablet_speaker_24_filled',
  'ic_fluent_tabs_24_filled',
  'ic_fluent_tag_24_filled',
  'ic_fluent_tag_dismiss_24_filled',
  'ic_fluent_tag_lock_24_filled',
  'ic_fluent_tag_lock_accent_24_filled',
  'ic_fluent_tag_question_mark_24_filled',
  'ic_fluent_tap_double_24_filled',
  'ic_fluent_tap_single_24_filled',
  'ic_fluent_target_24_filled',
  'ic_fluent_target_arrow_24_filled',
  'ic_fluent_target_edit_24_filled',
  'ic_fluent_task_list_add_24_filled',
  'ic_fluent_task_list_ltr_24_filled',
  'ic_fluent_task_list_rtl_24_filled',
  'ic_fluent_task_list_square_add_24_filled',
  'ic_fluent_task_list_square_ltr_24_filled',
  'ic_fluent_task_list_square_rtl_24_filled',
  'ic_fluent_tasks_app_24_filled',
  'ic_fluent_teddy_24_filled',
  'ic_fluent_temperature_24_filled',
  'ic_fluent_tent_24_filled',
  'ic_fluent_tetris_app_24_filled',
  'ic_fluent_text_24_filled',
  'ic_fluent_text_add_24_filled',
  'ic_fluent_text_add_space_after_24_filled',
  'ic_fluent_text_add_space_before_24_filled',
  'ic_fluent_text_add_t_24_filled',
  'ic_fluent_text_align_center_24_filled',
  'ic_fluent_text_align_center_rotate_270_24_filled',
  'ic_fluent_text_align_distributed_24_filled',
  'ic_fluent_text_align_distributed_evenly_24_filled',
  'ic_fluent_text_align_distributed_vertical_24_filled',
  'ic_fluent_text_align_justify_24_filled',
  'ic_fluent_text_align_justify_low_24_filled',
  'ic_fluent_text_align_justify_low_rotate_90_24_filled',
  'ic_fluent_text_align_justify_rotate_90_24_filled',
  'ic_fluent_text_align_left_24_filled',
  'ic_fluent_text_align_left_rotate_270_24_filled',
  'ic_fluent_text_align_right_24_filled',
  'ic_fluent_text_align_right_rotate_270_24_filled',
  'ic_fluent_text_bold_24_filled',
  'ic_fluent_text_bullet_list_add_24_filled',
  'ic_fluent_text_bullet_list_ltr_24_filled',
  'ic_fluent_text_bullet_list_rtl_24_filled',
  'ic_fluent_text_bullet_list_square_24_filled',
  'ic_fluent_text_bullet_list_square_edit_24_filled',
  'ic_fluent_text_bullet_list_square_warning_24_filled',
  'ic_fluent_text_bullet_list_tree_24_filled',
  'ic_fluent_text_case_lowercase_24_filled',
  'ic_fluent_text_case_title_24_filled',
  'ic_fluent_text_case_uppercase_24_filled',
  'ic_fluent_text_change_case_24_filled',
  'ic_fluent_text_clear_formatting_24_filled',
  'ic_fluent_text_clear_formatting_ga_24_filled',
  'ic_fluent_text_collapse_24_filled',
  'ic_fluent_text_color_24_filled',
  'ic_fluent_text_color_accent_24_filled',
  'ic_fluent_text_color_ga_24_filled',
  'ic_fluent_text_column_one_24_filled',
  'ic_fluent_text_column_one_narrow_24_filled',
  'ic_fluent_text_column_one_wide_24_filled',
  'ic_fluent_text_column_three_24_filled',
  'ic_fluent_text_column_two_24_filled',
  'ic_fluent_text_column_two_left_24_filled',
  'ic_fluent_text_column_two_right_24_filled',
  'ic_fluent_text_continuous_24_filled',
  'ic_fluent_text_description_24_filled',
  'ic_fluent_text_direction_horizontal_left_24_filled',
  'ic_fluent_text_direction_horizontal_ltr_24_filled',
  'ic_fluent_text_direction_horizontal_right_24_filled',
  'ic_fluent_text_direction_horizontal_rtl_24_filled',
  'ic_fluent_text_direction_rotate_270_ltr_24_filled',
  'ic_fluent_text_direction_rotate_270_right_24_filled',
  'ic_fluent_text_direction_rotate_90_left_24_filled',
  'ic_fluent_text_direction_rotate_90_ltr_24_filled',
  'ic_fluent_text_direction_rotate_90_right_24_filled',
  'ic_fluent_text_direction_rotate_90_rtl_24_filled',
  'ic_fluent_text_direction_vertical_24_filled',
  'ic_fluent_text_edit_style_24_filled',
  'ic_fluent_text_edit_style_ga_24_filled',
  'ic_fluent_text_effects_24_filled',
  'ic_fluent_text_effects_ga_24_filled',
  'ic_fluent_text_expand_24_filled',
  'ic_fluent_text_field_24_filled',
  'ic_fluent_text_first_line_24_filled',
  'ic_fluent_text_font_24_filled',
  'ic_fluent_text_font_size_24_filled',
  'ic_fluent_text_footnote_24_filled',
  'ic_fluent_text_footnote_ga_na_24_filled',
  'ic_fluent_text_grammar_arrow_left_24_filled',
  'ic_fluent_text_grammar_arrow_right_24_filled',
  'ic_fluent_text_grammar_checkmark_24_filled',
  'ic_fluent_text_grammar_dismiss_24_filled',
  'ic_fluent_text_grammar_settings_24_filled',
  'ic_fluent_text_grammar_wand_24_filled',
  'ic_fluent_text_hanging_24_filled',
  'ic_fluent_text_header_1_24_filled',
  'ic_fluent_text_header_2_24_filled',
  'ic_fluent_text_header_3_24_filled',
  'ic_fluent_text_indent_decrease_24_filled',
  'ic_fluent_text_indent_decrease_ltr_24_filled',
  'ic_fluent_text_indent_decrease_rtl_24_filled',
  'ic_fluent_text_indent_increase_24_filled',
  'ic_fluent_text_indent_increase_ltr_24_filled',
  'ic_fluent_text_indent_increase_rtl_24_filled',
  'ic_fluent_text_italic_24_filled',
  'ic_fluent_text_line_spacing_24_filled',
  'ic_fluent_text_more_24_filled',
  'ic_fluent_text_number_format_24_filled',
  'ic_fluent_text_number_format_ga_na_da_24_filled',
  'ic_fluent_text_number_list_ltr_24_filled',
  'ic_fluent_text_number_list_rtl_24_filled',
  'ic_fluent_text_paragraph_24_filled',
  'ic_fluent_text_paragraph_direction_24_filled',
  'ic_fluent_text_position_behind_24_filled',
  'ic_fluent_text_position_front_24_filled',
  'ic_fluent_text_position_line_24_filled',
  'ic_fluent_text_position_square_24_filled',
  'ic_fluent_text_position_through_24_filled',
  'ic_fluent_text_position_tight_24_filled',
  'ic_fluent_text_position_top_bottom_24_filled',
  'ic_fluent_text_proofing_tools_24_filled',
  'ic_fluent_text_proofing_tools_ga_na_da_24_filled',
  'ic_fluent_text_proofing_tools_zi_24_filled',
  'ic_fluent_text_quote_24_filled',
  'ic_fluent_text_sort_ascending_24_filled',
  'ic_fluent_text_sort_descending_24_filled',
  'ic_fluent_text_strikethrough_24_filled',
  'ic_fluent_text_strikethrough_s_24_filled',
  'ic_fluent_text_subscript_24_filled',
  'ic_fluent_text_superscript_24_filled',
  'ic_fluent_text_t_24_filled',
  'ic_fluent_text_underline_24_filled',
  'ic_fluent_text_word_count_24_filled',
  'ic_fluent_text_wrap_24_filled',
  'ic_fluent_textbox_24_filled',
  'ic_fluent_textbox_align_bottom_24_filled',
  'ic_fluent_textbox_align_bottom_rotate_90_24_filled',
  'ic_fluent_textbox_align_center_24_filled',
  'ic_fluent_textbox_align_middle_24_filled',
  'ic_fluent_textbox_align_middle_rotate_90_24_filled',
  'ic_fluent_textbox_align_top_24_filled',
  'ic_fluent_textbox_align_top_rotate_90_24_filled',
  'ic_fluent_textbox_more_24_filled',
  'ic_fluent_textbox_vertical_24_filled',
  'ic_fluent_thinking_24_filled',
  'ic_fluent_thumb_dislike_24_filled',
  'ic_fluent_thumb_like_24_filled',
  'ic_fluent_ticket_diagonal_24_filled',
  'ic_fluent_ticket_horizontal_24_filled',
  'ic_fluent_time_and_weather_24_filled',
  'ic_fluent_time_picker_24_filled',
  'ic_fluent_timeline_24_filled',
  'ic_fluent_timer_10_24_filled',
  'ic_fluent_timer_24_filled',
  'ic_fluent_timer_2_24_filled',
  'ic_fluent_timer_3_24_filled',
  'ic_fluent_timer_off_24_filled',
  'ic_fluent_toggle_left_24_filled',
  'ic_fluent_toggle_right_24_filled',
  'ic_fluent_toolbox_24_filled',
  'ic_fluent_tooltip_quote_24_filled',
  'ic_fluent_top_speed_24_filled',
  'ic_fluent_translate_24_filled',
  'ic_fluent_transmission_24_filled',
  'ic_fluent_trophy_24_filled',
  'ic_fluent_tv_24_filled',
  'ic_fluent_tv_usb_24_filled',
  'ic_fluent_umbrella_24_filled',
  'ic_fluent_uninstall_app_24_filled',
  'ic_fluent_usb_plug_24_filled',
  'ic_fluent_usb_port_24_filled',
  'ic_fluent_usb_stick_24_filled',
  'ic_fluent_vault_24_filled',
  'ic_fluent_vehicle_bicycle_24_filled',
  'ic_fluent_vehicle_bus_24_filled',
  'ic_fluent_vehicle_cab_24_filled',
  'ic_fluent_vehicle_car_24_filled',
  'ic_fluent_vehicle_car_collision_24_filled',
  'ic_fluent_vehicle_ship_24_filled',
  'ic_fluent_vehicle_subway_24_filled',
  'ic_fluent_vehicle_truck_24_filled',
  'ic_fluent_vehicle_truck_profile_24_filled',
  'ic_fluent_video_24_filled',
  'ic_fluent_video_360_24_filled',
  'ic_fluent_video_add_24_filled',
  'ic_fluent_video_background_effect_24_filled',
  'ic_fluent_video_clip_24_filled',
  'ic_fluent_video_off_24_filled',
  'ic_fluent_video_person_24_filled',
  'ic_fluent_video_person_call_24_filled',
  'ic_fluent_video_person_off_24_filled',
  'ic_fluent_video_person_sparkle_24_filled',
  'ic_fluent_video_person_star_24_filled',
  'ic_fluent_video_person_star_off_24_filled',
  'ic_fluent_video_play_pause_24_filled',
  'ic_fluent_video_prohibited_24_filled',
  'ic_fluent_video_security_24_filled',
  'ic_fluent_video_switch_24_filled',
  'ic_fluent_view_desktop_24_filled',
  'ic_fluent_view_desktop_mobile_24_filled',
  'ic_fluent_voicemail_24_filled',
  'ic_fluent_vote_24_filled',
  'ic_fluent_walkie_talkie_24_filled',
  'ic_fluent_wallet_24_filled',
  'ic_fluent_wallpaper_24_filled',
  'ic_fluent_wand_24_filled',
  'ic_fluent_warning_24_filled',
  'ic_fluent_weather_blowing_snow_24_filled',
  'ic_fluent_weather_cloudy_24_filled',
  'ic_fluent_weather_drizzle_24_filled',
  'ic_fluent_weather_duststorm_24_filled',
  'ic_fluent_weather_fog_24_filled',
  'ic_fluent_weather_hail_day_24_filled',
  'ic_fluent_weather_hail_night_24_filled',
  'ic_fluent_weather_haze_24_filled',
  'ic_fluent_weather_moon_24_filled',
  'ic_fluent_weather_moon_off_24_filled',
  'ic_fluent_weather_partly_cloudy_day_24_filled',
  'ic_fluent_weather_partly_cloudy_night_24_filled',
  'ic_fluent_weather_rain_24_filled',
  'ic_fluent_weather_rain_showers_day_24_filled',
  'ic_fluent_weather_rain_showers_night_24_filled',
  'ic_fluent_weather_rain_snow_24_filled',
  'ic_fluent_weather_snow_24_filled',
  'ic_fluent_weather_snow_shower_day_24_filled',
  'ic_fluent_weather_snow_shower_night_24_filled',
  'ic_fluent_weather_snowflake_24_filled',
  'ic_fluent_weather_squalls_24_filled',
  'ic_fluent_weather_sunny_24_filled',
  'ic_fluent_weather_sunny_high_24_filled',
  'ic_fluent_weather_sunny_low_24_filled',
  'ic_fluent_weather_thunderstorm_24_filled',
  'ic_fluent_web_asset_24_filled',
  'ic_fluent_whiteboard_24_filled',
  'ic_fluent_wifi_1_24_filled',
  'ic_fluent_wifi_2_24_filled',
  'ic_fluent_wifi_3_24_filled',
  'ic_fluent_wifi_4_24_filled',
  'ic_fluent_wifi_lock_24_filled',
  'ic_fluent_wifi_off_24_filled',
  'ic_fluent_wifi_protected_24_filled',
  'ic_fluent_wifi_warning_24_filled',
  'ic_fluent_window_24_filled',
  'ic_fluent_window_arrow_up_24_filled',
  'ic_fluent_window_dev_tools_24_filled',
  'ic_fluent_window_new_24_filled',
  'ic_fluent_window_shield_24_filled',
  'ic_fluent_wrench_24_filled',
  'ic_fluent_xbox_console_24_filled',
  'ic_fluent_xray_24_filled',
  'ic_fluent_zoom_in_24_filled',
  'ic_fluent_zoom_out_24_filled',
];


// @ ━━━━━━━━━━━━━━ Membuat List Icon dan Fungsi Drag and Drop ━━━━━━━━━━━━━━

	ul = document.getElementById("fluent-list");
	var render_lists = function(lists) {
		var li = "";
		for (index in lists) {
			li += "<li draggable='true' id='" + fileName[index] + "' class='col:2 bigButton'>" + "<div class='icon icon-normal fluent-" + fileName[index] + "'></div>" + "<span class='pt-2'>" + iconName[index] + "</span>" + "</li>";
		}
		ul.innerHTML = li;
	}
	render_lists(fileName);
	fileName.forEach((fileName, index) => {
		document.getElementById(fileName).ondragstart = (event) => {
			event.preventDefault()
			window.electron.startDrag('./../data/fluent-icons-filled/svg/' + fileName + '.svg')
			console.log('drag to mana kek')
		}
	});



  $("#myInput").keyup(function() {
    var input, filter, ul, li, span, i, txtValue;
    input = document.getElementById('myInput');
    filter = input.value.toUpperCase();
    ul = document.getElementById("fluent-list");
    li = ul.getElementsByTagName('li');
  
    // Loop through all list items, and hide those who don't match the search query
    for (i = 0; i < li.length; i++) {
      span = li[i].getElementsByTagName("span")[0];
      txtValue = span.textContent || span.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        li[i].style.display = "";
      } else {
        li[i].style.display = "none";
      }
    }
  });
